import type { Question, Story, VocabWord } from "../types";
import { TOPICS } from "../types";

export const topics: string[] = [...TOPICS];

export const vocabulary: VocabWord[] = [
  // ── Animals (45) ──────────────────────────────────────────────
  { id: 1, word: "dog", meaning_vi: "con chó", emoji: "🐶", topic: "animals", level: 0, example_en: "The dog runs.", example_vi: "Con chó chạy.", part_of_speech: "noun" },
  { id: 2, word: "cat", meaning_vi: "con mèo", emoji: "🐱", topic: "animals", level: 0, example_en: "The cat sleeps.", example_vi: "Con mèo ngủ.", part_of_speech: "noun" },
  { id: 3, word: "fish", meaning_vi: "con cá", emoji: "🐟", topic: "animals", level: 0, example_en: "Fish swim.", example_vi: "Cá bơi.", part_of_speech: "noun" },
  { id: 4, word: "bird", meaning_vi: "con chim", emoji: "🐦", topic: "animals", level: 0, example_en: "Birds fly.", example_vi: "Chim bay.", part_of_speech: "noun" },
  { id: 5, word: "horse", meaning_vi: "con ngựa", emoji: "🐴", topic: "animals", level: 0, example_en: "The horse runs.", example_vi: "Con ngựa chạy.", part_of_speech: "noun" },
  { id: 6, word: "pig", meaning_vi: "con lợn", emoji: "🐷", topic: "animals", level: 0, example_en: "The pig is pink.", example_vi: "Con lợn hồng.", part_of_speech: "noun" },
  { id: 7, word: "cow", meaning_vi: "con bò", emoji: "🐮", topic: "animals", level: 0, example_en: "The cow eats grass.", example_vi: "Con bò ăn cỏ.", part_of_speech: "noun" },
  { id: 8, word: "duck", meaning_vi: "con vịt", emoji: "🦆", topic: "animals", level: 0, example_en: "Ducks swim.", example_vi: "Vịt bơi.", part_of_speech: "noun" },
  { id: 9, word: "chicken", meaning_vi: "con gà", emoji: "🐔", topic: "animals", level: 0, example_en: "The chicken is small.", example_vi: "Con gà nhỏ.", part_of_speech: "noun" },
  { id: 10, word: "sheep", meaning_vi: "con cừu", emoji: "🐑", topic: "animals", level: 0, example_en: "Sheep are white.", example_vi: "Cừu màu trắng.", part_of_speech: "noun" },
  { id: 11, word: "goat", meaning_vi: "con dê", emoji: "🐐", topic: "animals", level: 0, example_en: "The goat jumps.", example_vi: "Con dê nhảy.", part_of_speech: "noun" },
  { id: 12, word: "rabbit", meaning_vi: "con thỏ", emoji: "🐰", topic: "animals", level: 0, example_en: "The rabbit hops.", example_vi: "Con thỏ nhảy.", part_of_speech: "noun" },
  { id: 13, word: "lion", meaning_vi: "sư tử", emoji: "🦁", topic: "animals", level: 0, example_en: "The lion roars.", example_vi: "Sư tử gầm.", part_of_speech: "noun" },
  { id: 14, word: "tiger", meaning_vi: "con hổ", emoji: "🐯", topic: "animals", level: 0, example_en: "The tiger is big.", example_vi: "Con hổ to.", part_of_speech: "noun" },
  { id: 15, word: "bear", meaning_vi: "con gấu", emoji: "🐻", topic: "animals", level: 0, example_en: "The bear is brown.", example_vi: "Con gấu nâu.", part_of_speech: "noun" },
  { id: 16, word: "monkey", meaning_vi: "con khỉ", emoji: "🐵", topic: "animals", level: 0, example_en: "The monkey climbs.", example_vi: "Con khỉ trèo.", part_of_speech: "noun" },
  { id: 17, word: "elephant", meaning_vi: "con voi", emoji: "🐘", topic: "animals", level: 0, example_en: "The elephant is huge.", example_vi: "Con voi khổng lồ.", part_of_speech: "noun" },
  { id: 18, word: "giraffe", meaning_vi: "hươu cao cổ", emoji: "🦒", topic: "animals", level: 0, example_en: "The giraffe is tall.", example_vi: "Hươu cao cổ cao.", part_of_speech: "noun" },
  { id: 19, word: "zebra", meaning_vi: "ngựa vằn", emoji: "🦓", topic: "animals", level: 0, example_en: "The zebra has stripes.", example_vi: "Ngựa vằn có sọc.", part_of_speech: "noun" },
  { id: 20, word: "snake", meaning_vi: "con rắn", emoji: "🐍", topic: "animals", level: 0, example_en: "The snake is long.", example_vi: "Con rắn dài.", part_of_speech: "noun" },
  { id: 21, word: "frog", meaning_vi: "con ếch", emoji: "🐸", topic: "animals", level: 0, example_en: "The frog jumps.", example_vi: "Con ếch nhảy.", part_of_speech: "noun" },
  { id: 22, word: "mouse", meaning_vi: "con chuột", emoji: "🐭", topic: "animals", level: 0, example_en: "The mouse is tiny.", example_vi: "Con chuột bé.", part_of_speech: "noun" },
  { id: 23, word: "fox", meaning_vi: "con cáo", emoji: "🦊", topic: "animals", level: 0, example_en: "The fox is red.", example_vi: "Con cáo đỏ.", part_of_speech: "noun" },
  { id: 24, word: "wolf", meaning_vi: "chó sói", emoji: "🐺", topic: "animals", level: 0, example_en: "The wolf howls.", example_vi: "Chó sói hú.", part_of_speech: "noun" },
  { id: 25, word: "deer", meaning_vi: "con nai", emoji: "🦌", topic: "animals", level: 0, example_en: "The deer runs.", example_vi: "Con nai chạy.", part_of_speech: "noun" },
  { id: 26, word: "owl", meaning_vi: "con cú", emoji: "🦉", topic: "animals", level: 0, example_en: "The owl is awake.", example_vi: "Con cú thức.", part_of_speech: "noun" },
  { id: 27, word: "bee", meaning_vi: "con ong", emoji: "🐝", topic: "animals", level: 0, example_en: "The bee flies.", example_vi: "Con ong bay.", part_of_speech: "noun" },
  { id: 28, word: "ant", meaning_vi: "con kiến", emoji: "🐜", topic: "animals", level: 0, example_en: "The ant is small.", example_vi: "Con kiến nhỏ.", part_of_speech: "noun" },
  { id: 29, word: "butterfly", meaning_vi: "con bướm", emoji: "🦋", topic: "animals", level: 0, example_en: "The butterfly is pretty.", example_vi: "Con bướm đẹp.", part_of_speech: "noun" },
  { id: 30, word: "spider", meaning_vi: "con nhện", emoji: "🕷️", topic: "animals", level: 0, example_en: "The spider spins.", example_vi: "Con nhện giăng tơ.", part_of_speech: "noun" },
  { id: 31, word: "crab", meaning_vi: "con cua", emoji: "🦀", topic: "animals", level: 0, example_en: "The crab walks.", example_vi: "Con cua bò.", part_of_speech: "noun" },
  { id: 32, word: "whale", meaning_vi: "cá voi", emoji: "🐳", topic: "animals", level: 0, example_en: "The whale is big.", example_vi: "Cá voi to.", part_of_speech: "noun" },
  { id: 33, word: "shark", meaning_vi: "cá mập", emoji: "🦈", topic: "animals", level: 0, example_en: "The shark swims.", example_vi: "Cá mập bơi.", part_of_speech: "noun" },
  { id: 34, word: "dolphin", meaning_vi: "cá heo", emoji: "🐬", topic: "animals", level: 0, example_en: "The dolphin plays.", example_vi: "Cá heo chơi.", part_of_speech: "noun" },
  { id: 35, word: "octopus", meaning_vi: "bạch tuộc", emoji: "🐙", topic: "animals", level: 0, example_en: "The octopus has arms.", example_vi: "Bạch tuộc có vòi.", part_of_speech: "noun" },
  { id: 36, word: "turtle", meaning_vi: "con rùa", emoji: "🐢", topic: "animals", level: 0, example_en: "The turtle is slow.", example_vi: "Con rùa chậm.", part_of_speech: "noun" },
  { id: 37, word: "panda", meaning_vi: "gấu trúc", emoji: "🐼", topic: "animals", level: 0, example_en: "The panda eats.", example_vi: "Gấu trúc ăn.", part_of_speech: "noun" },
  { id: 38, word: "koala", meaning_vi: "gấu túi", emoji: "🐨", topic: "animals", level: 0, example_en: "The koala sleeps.", example_vi: "Gấu túi ngủ.", part_of_speech: "noun" },
  { id: 39, word: "kangaroo", meaning_vi: "chuột túi", emoji: "🦘", topic: "animals", level: 0, example_en: "The kangaroo jumps.", example_vi: "Chuột túi nhảy.", part_of_speech: "noun" },
  { id: 40, word: "camel", meaning_vi: "lạc đà", emoji: "🐫", topic: "animals", level: 0, example_en: "The camel walks.", example_vi: "Lạc đà đi.", part_of_speech: "noun" },
  { id: 41, word: "rooster", meaning_vi: "con gà trống", emoji: "🐓", topic: "animals", level: 0, example_en: "The rooster crows.", example_vi: "Gà trống gáy.", part_of_speech: "noun" },
  { id: 42, word: "penguin", meaning_vi: "chim cánh cụt", emoji: "🐧", topic: "animals", level: 0, example_en: "The penguin waddles.", example_vi: "Chim cánh cụt đi.", part_of_speech: "noun" },
  { id: 43, word: "peacock", meaning_vi: "con công", emoji: "🦚", topic: "animals", level: 0, example_en: "The peacock is pretty.", example_vi: "Con công đẹp.", part_of_speech: "noun" },
  { id: 44, word: "snail", meaning_vi: "con ốc sên", emoji: "🐌", topic: "animals", level: 0, example_en: "The snail is slow.", example_vi: "Con ốc sên chậm.", part_of_speech: "noun" },
  { id: 45, word: "ladybug", meaning_vi: "con bọ rùa", emoji: "🐞", topic: "animals", level: 0, example_en: "The ladybug is red.", example_vi: "Con bọ rùa đỏ.", part_of_speech: "noun" },

  // ── Food (20) ─────────────────────────────────────────────────
  { id: 46, word: "rice", meaning_vi: "cơm", emoji: "🍚", topic: "food", level: 0, example_en: "I eat rice.", example_vi: "Em ăn cơm.", part_of_speech: "noun" },
  { id: 47, word: "bread", meaning_vi: "bánh mì", emoji: "🍞", topic: "food", level: 0, example_en: "Bread is tasty.", example_vi: "Bánh mì ngon.", part_of_speech: "noun" },
  { id: 48, word: "milk", meaning_vi: "sữa", emoji: "🥛", topic: "food", level: 0, example_en: "I drink milk.", example_vi: "Em uống sữa.", part_of_speech: "noun" },
  { id: 49, word: "egg", meaning_vi: "trứng", emoji: "🥚", topic: "food", level: 0, example_en: "The egg is round.", example_vi: "Trứng tròn.", part_of_speech: "noun" },
  { id: 50, word: "cake", meaning_vi: "bánh ngọt", emoji: "🎂", topic: "food", level: 0, example_en: "Cake is sweet.", example_vi: "Bánh ngọt.", part_of_speech: "noun" },
  { id: 51, word: "candy", meaning_vi: "kẹo", emoji: "🍬", topic: "food", level: 0, example_en: "Candy is sweet.", example_vi: "Kẹo ngọt.", part_of_speech: "noun" },
  { id: 52, word: "water", meaning_vi: "nước", emoji: "💧", topic: "food", level: 0, example_en: "Drink water.", example_vi: "Uống nước.", part_of_speech: "noun" },
  { id: 53, word: "soup", meaning_vi: "súp", emoji: "🍲", topic: "food", level: 0, example_en: "Soup is hot.", example_vi: "Súp nóng.", part_of_speech: "noun" },
  { id: 54, word: "meat", meaning_vi: "thịt", emoji: "🍖", topic: "food", level: 0, example_en: "I eat meat.", example_vi: "Em ăn thịt.", part_of_speech: "noun" },
  { id: 55, word: "noodle", meaning_vi: "mì", emoji: "🍜", topic: "food", level: 0, example_en: "Noodles are long.", example_vi: "Mì dài.", part_of_speech: "noun" },
  { id: 56, word: "cheese", meaning_vi: "phô mai", emoji: "🧀", topic: "food", level: 0, example_en: "Cheese is yellow.", example_vi: "Phô mai vàng.", part_of_speech: "noun" },
  { id: 57, word: "honey", meaning_vi: "mật ong", emoji: "🍯", topic: "food", level: 0, example_en: "Honey is sweet.", example_vi: "Mật ong ngọt.", part_of_speech: "noun" },
  { id: 58, word: "juice", meaning_vi: "nước ép", emoji: "🧃", topic: "food", level: 0, example_en: "I like juice.", example_vi: "Em thích nước ép.", part_of_speech: "noun" },
  { id: 59, word: "tea", meaning_vi: "trà", emoji: "🍵", topic: "food", level: 0, example_en: "Tea is warm.", example_vi: "Trà ấm.", part_of_speech: "noun" },
  { id: 60, word: "cookie", meaning_vi: "bánh quy", emoji: "🍪", topic: "food", level: 0, example_en: "Cookies are crunchy.", example_vi: "Bánh quy giòn.", part_of_speech: "noun" },
  { id: 61, word: "pizza", meaning_vi: "bánh pizza", emoji: "🍕", topic: "food", level: 0, example_en: "Pizza is round.", example_vi: "Pizza tròn.", part_of_speech: "noun" },
  { id: 62, word: "ice cream", meaning_vi: "kem", emoji: "🍦", topic: "food", level: 0, example_en: "Ice cream is cold.", example_vi: "Kem lạnh.", part_of_speech: "noun" },
  { id: 63, word: "jam", meaning_vi: "mứt", emoji: "🍓", topic: "food", level: 0, example_en: "Jam is sweet.", example_vi: "Mứt ngọt.", part_of_speech: "noun" },
  { id: 64, word: "corn", meaning_vi: "ngô", emoji: "🌽", topic: "food", level: 0, example_en: "Corn is yellow.", example_vi: "Ngô vàng.", part_of_speech: "noun" },
  { id: 65, word: "fries", meaning_vi: "khoai tây chiên", emoji: "🍟", topic: "food", level: 0, example_en: "Fries are hot.", example_vi: "Khoai chiên nóng.", part_of_speech: "noun" },

  // ── Family (16) ───────────────────────────────────────────────
  { id: 66, word: "mother", meaning_vi: "mẹ", emoji: "👩", topic: "family", level: 0, example_en: "Mother is kind.", example_vi: "Mẹ hiền.", part_of_speech: "noun" },
  { id: 67, word: "father", meaning_vi: "bố", emoji: "👨", topic: "family", level: 0, example_en: "Father is tall.", example_vi: "Bố cao.", part_of_speech: "noun" },
  { id: 68, word: "sister", meaning_vi: "chị gái", emoji: "👧", topic: "family", level: 0, example_en: "Sister is young.", example_vi: "Chị trẻ.", part_of_speech: "noun" },
  { id: 69, word: "brother", meaning_vi: "anh trai", emoji: "👦", topic: "family", level: 0, example_en: "Brother runs.", example_vi: "Anh trai chạy.", part_of_speech: "noun" },
  { id: 70, word: "baby", meaning_vi: "em bé", emoji: "👶", topic: "family", level: 0, example_en: "Baby laughs.", example_vi: "Em bé cười.", part_of_speech: "noun" },
  { id: 71, word: "grandma", meaning_vi: "bà", emoji: "👵", topic: "family", level: 0, example_en: "Grandma cooks.", example_vi: "Bà nấu ăn.", part_of_speech: "noun" },
  { id: 72, word: "grandpa", meaning_vi: "ông", emoji: "👴", topic: "family", level: 0, example_en: "Grandpa reads.", example_vi: "Ông đọc sách.", part_of_speech: "noun" },
  { id: 73, word: "family", meaning_vi: "gia đình", emoji: "👨‍👩‍👧‍👦", topic: "family", level: 0, example_en: "I love my family.", example_vi: "Em yêu gia đình.", part_of_speech: "noun" },
  { id: 74, word: "son", meaning_vi: "con trai", emoji: "🧒", topic: "family", level: 0, example_en: "The son is happy.", example_vi: "Con trai vui.", part_of_speech: "noun" },
  { id: 75, word: "daughter", meaning_vi: "con gái", emoji: "👧", topic: "family", level: 0, example_en: "The daughter sings.", example_vi: "Con gái hát.", part_of_speech: "noun" },
  { id: 76, word: "aunt", meaning_vi: "cô", emoji: "👩", topic: "family", level: 0, example_en: "My aunt is nice.", example_vi: "Cô em tốt.", part_of_speech: "noun" },
  { id: 77, word: "uncle", meaning_vi: "chú", emoji: "👨", topic: "family", level: 0, example_en: "My uncle is tall.", example_vi: "Chú em cao.", part_of_speech: "noun" },
  { id: 78, word: "cousin", meaning_vi: "anh chị em họ", emoji: "🧑", topic: "family", level: 0, example_en: "My cousin plays.", example_vi: "Anh họ chơi.", part_of_speech: "noun" },
  { id: 79, word: "boy", meaning_vi: "cậu bé", emoji: "👦", topic: "family", level: 0, example_en: "The boy runs.", example_vi: "Cậu bé chạy.", part_of_speech: "noun" },
  { id: 80, word: "girl", meaning_vi: "cô bé", emoji: "👧", topic: "family", level: 0, example_en: "The girl smiles.", example_vi: "Cô bé cười.", part_of_speech: "noun" },
  { id: 81, word: "friend", meaning_vi: "bạn", emoji: "🧑‍🤝‍🧑", topic: "family", level: 0, example_en: "I have a friend.", example_vi: "Em có một người bạn.", part_of_speech: "noun" },

  // ── Body (18) ─────────────────────────────────────────────────
  { id: 82, word: "head", meaning_vi: "đầu", emoji: "👤", topic: "body", level: 0, example_en: "Nod your head.", example_vi: "Gật đầu.", part_of_speech: "noun" },
  { id: 83, word: "eye", meaning_vi: "mắt", emoji: "👁️", topic: "body", level: 0, example_en: "Close your eyes.", example_vi: "Nhắm mắt.", part_of_speech: "noun" },
  { id: 84, word: "ear", meaning_vi: "tai", emoji: "👂", topic: "body", level: 0, example_en: "Listen with ears.", example_vi: "Nghe bằng tai.", part_of_speech: "noun" },
  { id: 85, word: "nose", meaning_vi: "mũi", emoji: "👃", topic: "body", level: 0, example_en: "Touch your nose.", example_vi: "Sờ mũi.", part_of_speech: "noun" },
  { id: 86, word: "mouth", meaning_vi: "miệng", emoji: "👄", topic: "body", level: 0, example_en: "Open your mouth.", example_vi: "Há miệng.", part_of_speech: "noun" },
  { id: 87, word: "hand", meaning_vi: "bàn tay", emoji: "✋", topic: "body", level: 0, example_en: "Wash your hands.", example_vi: "Rửa tay.", part_of_speech: "noun" },
  { id: 88, word: "foot", meaning_vi: "bàn chân", emoji: "🦶", topic: "body", level: 0, example_en: "My foot is small.", example_vi: "Bàn chân em nhỏ.", part_of_speech: "noun" },
  { id: 89, word: "arm", meaning_vi: "cánh tay", emoji: "💪", topic: "body", level: 0, example_en: "Raise your arm.", example_vi: "Giơ cánh tay.", part_of_speech: "noun" },
  { id: 90, word: "leg", meaning_vi: "chân", emoji: "🦵", topic: "body", level: 0, example_en: "My legs are long.", example_vi: "Chân em dài.", part_of_speech: "noun" },
  { id: 91, word: "hair", meaning_vi: "tóc", emoji: "💇", topic: "body", level: 0, example_en: "Her hair is long.", example_vi: "Tóc cô ấy dài.", part_of_speech: "noun" },
  { id: 92, word: "finger", meaning_vi: "ngón tay", emoji: "👆", topic: "body", level: 0, example_en: "I have ten fingers.", example_vi: "Em có mười ngón tay.", part_of_speech: "noun" },
  { id: 93, word: "tooth", meaning_vi: "răng", emoji: "🦷", topic: "body", level: 0, example_en: "Brush your tooth.", example_vi: "Đánh răng.", part_of_speech: "noun" },
  { id: 94, word: "face", meaning_vi: "khuôn mặt", emoji: "😀", topic: "body", level: 0, example_en: "Wash your face.", example_vi: "Rửa mặt.", part_of_speech: "noun" },
  { id: 95, word: "tongue", meaning_vi: "lưỡi", emoji: "👅", topic: "body", level: 0, example_en: "Show your tongue.", example_vi: "Lè lưỡi.", part_of_speech: "noun" },
  { id: 96, word: "bone", meaning_vi: "xương", emoji: "🦴", topic: "body", level: 0, example_en: "Bones are hard.", example_vi: "Xương cứng.", part_of_speech: "noun" },
  { id: 97, word: "brain", meaning_vi: "não", emoji: "🧠", topic: "body", level: 0, example_en: "I think with my brain.", example_vi: "Em nghĩ bằng não.", part_of_speech: "noun" },
  { id: 98, word: "heart", meaning_vi: "trái tim", emoji: "❤️", topic: "body", level: 0, example_en: "My heart beats.", example_vi: "Tim em đập.", part_of_speech: "noun" },
  { id: 99, word: "thumb", meaning_vi: "ngón cái", emoji: "👍", topic: "body", level: 0, example_en: "Thumbs up!", example_vi: "Giơ ngón cái!", part_of_speech: "noun" },

  // ── Colors (15) ───────────────────────────────────────────────
  { id: 100, word: "red", meaning_vi: "đỏ", emoji: "🔴", topic: "colors", level: 0, example_en: "The apple is red.", example_vi: "Táo đỏ.", part_of_speech: "adj" },
  { id: 101, word: "blue", meaning_vi: "xanh dương", emoji: "🔵", topic: "colors", level: 0, example_en: "The sky is blue.", example_vi: "Trời xanh.", part_of_speech: "adj" },
  { id: 102, word: "green", meaning_vi: "xanh lá", emoji: "🟢", topic: "colors", level: 0, example_en: "Grass is green.", example_vi: "Cỏ xanh.", part_of_speech: "adj" },
  { id: 103, word: "yellow", meaning_vi: "vàng", emoji: "🟡", topic: "colors", level: 0, example_en: "The sun is yellow.", example_vi: "Mặt trời vàng.", part_of_speech: "adj" },
  { id: 104, word: "white", meaning_vi: "trắng", emoji: "⚪", topic: "colors", level: 0, example_en: "Snow is white.", example_vi: "Tuyết trắng.", part_of_speech: "adj" },
  { id: 105, word: "black", meaning_vi: "đen", emoji: "⚫", topic: "colors", level: 0, example_en: "Night is black.", example_vi: "Đêm đen.", part_of_speech: "adj" },
  { id: 106, word: "pink", meaning_vi: "hồng", emoji: "🩷", topic: "colors", level: 0, example_en: "The flower is pink.", example_vi: "Hoa hồng.", part_of_speech: "adj" },
  { id: 107, word: "orange", meaning_vi: "cam", emoji: "🟠", topic: "colors", level: 0, example_en: "The ball is orange.", example_vi: "Quả bóng cam.", part_of_speech: "adj" },
  { id: 108, word: "purple", meaning_vi: "tím", emoji: "🟣", topic: "colors", level: 0, example_en: "The grape is purple.", example_vi: "Nho tím.", part_of_speech: "adj" },
  { id: 109, word: "brown", meaning_vi: "nâu", emoji: "🟤", topic: "colors", level: 0, example_en: "The bear is brown.", example_vi: "Con gấu nâu.", part_of_speech: "adj" },
  { id: 110, word: "gray", meaning_vi: "xám", emoji: "🩶", topic: "colors", level: 0, example_en: "The cloud is gray.", example_vi: "Mây xám.", part_of_speech: "adj" },
  { id: 111, word: "gold", meaning_vi: "vàng kim", emoji: "🥇", topic: "colors", level: 0, example_en: "The medal is gold.", example_vi: "Huy chương vàng.", part_of_speech: "adj" },
  { id: 112, word: "silver", meaning_vi: "bạc", emoji: "🥈", topic: "colors", level: 0, example_en: "The coin is silver.", example_vi: "Đồng xu bạc.", part_of_speech: "adj" },
  { id: 113, word: "rainbow", meaning_vi: "cầu vồng", emoji: "🌈", topic: "colors", level: 0, example_en: "I see a rainbow.", example_vi: "Em thấy cầu vồng.", part_of_speech: "noun" },
  { id: 114, word: "violet", meaning_vi: "tím nhạt", emoji: "💜", topic: "colors", level: 0, example_en: "The petal is violet.", example_vi: "Cánh hoa tím.", part_of_speech: "adj" },

  // ── Toys (12) ─────────────────────────────────────────────────
  { id: 115, word: "ball", meaning_vi: "quả bóng", emoji: "⚽", topic: "toys", level: 0, example_en: "I play ball.", example_vi: "Em chơi bóng.", part_of_speech: "noun" },
  { id: 116, word: "doll", meaning_vi: "búp bê", emoji: "🎎", topic: "toys", level: 0, example_en: "The doll is pretty.", example_vi: "Búp bê đẹp.", part_of_speech: "noun" },
  { id: 117, word: "robot", meaning_vi: "rô bốt", emoji: "🤖", topic: "toys", level: 0, example_en: "The robot talks.", example_vi: "Rô bốt nói.", part_of_speech: "noun" },
  { id: 118, word: "kite", meaning_vi: "cái diều", emoji: "🪁", topic: "toys", level: 0, example_en: "Fly a kite.", example_vi: "Thả diều.", part_of_speech: "noun" },
  { id: 119, word: "puzzle", meaning_vi: "trò xếp hình", emoji: "🧩", topic: "toys", level: 0, example_en: "Solve the puzzle.", example_vi: "Xếp hình.", part_of_speech: "noun" },
  { id: 120, word: "car", meaning_vi: "ô tô đồ chơi", emoji: "🚗", topic: "toys", level: 0, example_en: "The toy car is fast.", example_vi: "Xe đồ chơi nhanh.", part_of_speech: "noun" },
  { id: 121, word: "blocks", meaning_vi: "khối xếp", emoji: "🧱", topic: "toys", level: 0, example_en: "I build with blocks.", example_vi: "Em xếp khối.", part_of_speech: "noun" },
  { id: 122, word: "teddy", meaning_vi: "gấu bông", emoji: "🧸", topic: "toys", level: 0, example_en: "I hug my teddy.", example_vi: "Em ôm gấu bông.", part_of_speech: "noun" },
  { id: 123, word: "yoyo", meaning_vi: "con quay yoyo", emoji: "🪀", topic: "toys", level: 0, example_en: "The yoyo spins.", example_vi: "Yoyo quay.", part_of_speech: "noun" },
  { id: 124, word: "drum", meaning_vi: "cái trống", emoji: "🥁", topic: "toys", level: 0, example_en: "I play the drum.", example_vi: "Em đánh trống.", part_of_speech: "noun" },
  { id: 125, word: "train", meaning_vi: "tàu đồ chơi", emoji: "🚂", topic: "toys", level: 0, example_en: "The toy train goes.", example_vi: "Tàu đồ chơi chạy.", part_of_speech: "noun" },
  { id: 126, word: "balloon", meaning_vi: "bóng bay", emoji: "🎈", topic: "toys", level: 0, example_en: "The balloon floats.", example_vi: "Bóng bay bay lên.", part_of_speech: "noun" },

  // ── Shapes (12) ───────────────────────────────────────────────
  { id: 127, word: "circle", meaning_vi: "hình tròn", emoji: "⭕", topic: "shapes", level: 0, example_en: "A wheel is a circle.", example_vi: "Bánh xe là hình tròn.", part_of_speech: "noun" },
  { id: 128, word: "square", meaning_vi: "hình vuông", emoji: "🟦", topic: "shapes", level: 0, example_en: "A box is a square.", example_vi: "Cái hộp hình vuông.", part_of_speech: "noun" },
  { id: 129, word: "triangle", meaning_vi: "hình tam giác", emoji: "🔺", topic: "shapes", level: 0, example_en: "A roof is a triangle.", example_vi: "Mái nhà hình tam giác.", part_of_speech: "noun" },
  { id: 130, word: "star", meaning_vi: "ngôi sao", emoji: "⭐", topic: "shapes", level: 0, example_en: "I draw a star.", example_vi: "Em vẽ ngôi sao.", part_of_speech: "noun" },
  { id: 131, word: "heart", meaning_vi: "hình trái tim", emoji: "❤️", topic: "shapes", level: 0, example_en: "I draw a heart.", example_vi: "Em vẽ trái tim.", part_of_speech: "noun" },
  { id: 132, word: "diamond", meaning_vi: "hình thoi", emoji: "💎", topic: "shapes", level: 0, example_en: "A kite is a diamond.", example_vi: "Cái diều hình thoi.", part_of_speech: "noun" },
  { id: 133, word: "oval", meaning_vi: "hình bầu dục", emoji: "🥚", topic: "shapes", level: 0, example_en: "An egg is an oval.", example_vi: "Quả trứng hình bầu dục.", part_of_speech: "noun" },
  { id: 134, word: "rectangle", meaning_vi: "hình chữ nhật", emoji: "🟥", topic: "shapes", level: 0, example_en: "A door is a rectangle.", example_vi: "Cái cửa hình chữ nhật.", part_of_speech: "noun" },
  { id: 135, word: "cross", meaning_vi: "hình chữ thập", emoji: "➕", topic: "shapes", level: 0, example_en: "I draw a cross.", example_vi: "Em vẽ chữ thập.", part_of_speech: "noun" },
  { id: 136, word: "ring", meaning_vi: "hình vòng", emoji: "💍", topic: "shapes", level: 0, example_en: "A ring is round.", example_vi: "Cái nhẫn tròn.", part_of_speech: "noun" },
  { id: 137, word: "line", meaning_vi: "đường thẳng", emoji: "➖", topic: "shapes", level: 0, example_en: "I draw a line.", example_vi: "Em vẽ một đường.", part_of_speech: "noun" },
  { id: 138, word: "dot", meaning_vi: "chấm tròn", emoji: "🔘", topic: "shapes", level: 0, example_en: "A dot is small.", example_vi: "Chấm tròn nhỏ.", part_of_speech: "noun" },

  // ── Numbers (12) ──────────────────────────────────────────────
  { id: 139, word: "zero", meaning_vi: "số không", emoji: "0️⃣", topic: "numbers", level: 0, example_en: "Zero means none.", example_vi: "Số không là không có gì.", part_of_speech: "num" },
  { id: 140, word: "one", meaning_vi: "số một", emoji: "1️⃣", topic: "numbers", level: 0, example_en: "I have one cat.", example_vi: "Em có một con mèo.", part_of_speech: "num" },
  { id: 141, word: "two", meaning_vi: "số hai", emoji: "2️⃣", topic: "numbers", level: 0, example_en: "I have two eyes.", example_vi: "Em có hai mắt.", part_of_speech: "num" },
  { id: 142, word: "three", meaning_vi: "số ba", emoji: "3️⃣", topic: "numbers", level: 0, example_en: "Three birds fly.", example_vi: "Ba con chim bay.", part_of_speech: "num" },
  { id: 143, word: "four", meaning_vi: "số bốn", emoji: "4️⃣", topic: "numbers", level: 0, example_en: "A car has four wheels.", example_vi: "Ô tô có bốn bánh.", part_of_speech: "num" },
  { id: 144, word: "five", meaning_vi: "số năm", emoji: "5️⃣", topic: "numbers", level: 0, example_en: "I have five fingers.", example_vi: "Em có năm ngón tay.", part_of_speech: "num" },
  { id: 145, word: "six", meaning_vi: "số sáu", emoji: "6️⃣", topic: "numbers", level: 0, example_en: "Six is after five.", example_vi: "Sáu sau năm.", part_of_speech: "num" },
  { id: 146, word: "seven", meaning_vi: "số bảy", emoji: "7️⃣", topic: "numbers", level: 0, example_en: "A week has seven days.", example_vi: "Một tuần có bảy ngày.", part_of_speech: "num" },
  { id: 147, word: "eight", meaning_vi: "số tám", emoji: "8️⃣", topic: "numbers", level: 0, example_en: "A spider has eight legs.", example_vi: "Nhện có tám chân.", part_of_speech: "num" },
  { id: 148, word: "nine", meaning_vi: "số chín", emoji: "9️⃣", topic: "numbers", level: 0, example_en: "Nine is before ten.", example_vi: "Chín trước mười.", part_of_speech: "num" },
  { id: 149, word: "ten", meaning_vi: "số mười", emoji: "🔟", topic: "numbers", level: 0, example_en: "I count to ten.", example_vi: "Em đếm đến mười.", part_of_speech: "num" },
  { id: 150, word: "eleven", meaning_vi: "số mười một", emoji: "🔢", topic: "numbers", level: 0, example_en: "Eleven is after ten.", example_vi: "Mười một sau mười.", part_of_speech: "num" },
];

export const questions: Question[] = [
  { id: 1, content: "What does \"dog\" mean?", options: ["con chó", "con mèo", "con cá", "con chim"], correct_index: 0, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"dog\" có nghĩa là con chó." },
  { id: 2, content: "What does \"cat\" mean?", options: ["con bò", "con mèo", "con vịt", "con gà"], correct_index: 1, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"cat\" có nghĩa là con mèo." },
  { id: 3, content: "What does \"fish\" mean?", options: ["con cá", "con thỏ", "con dê", "con cừu"], correct_index: 0, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"fish\" có nghĩa là con cá." },
  { id: 4, content: "What does \"bird\" mean?", options: ["sư tử", "con hổ", "con chim", "con gấu"], correct_index: 2, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"bird\" có nghĩa là con chim." },
  { id: 5, content: "What does \"lion\" mean?", options: ["sư tử", "con khỉ", "con voi", "con rắn"], correct_index: 0, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"lion\" có nghĩa là sư tử." },
  { id: 6, content: "What does \"elephant\" mean?", options: ["con cáo", "con voi", "con nai", "con ong"], correct_index: 1, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"elephant\" có nghĩa là con voi." },
  { id: 7, content: "What does \"rabbit\" mean?", options: ["con kiến", "con bướm", "con thỏ", "con nhện"], correct_index: 2, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"rabbit\" có nghĩa là con thỏ." },
  { id: 8, content: "What does \"bear\" mean?", options: ["con gấu", "cá voi", "cá mập", "cá heo"], correct_index: 0, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"bear\" có nghĩa là con gấu." },
  { id: 9, content: "What does \"monkey\" mean?", options: ["con rùa", "gấu trúc", "con khỉ", "con công"], correct_index: 2, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"monkey\" có nghĩa là con khỉ." },
  { id: 10, content: "What does \"tiger\" mean?", options: ["con hổ", "lạc đà", "con rắn", "con ếch"], correct_index: 0, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"tiger\" có nghĩa là con hổ." },
  { id: 11, content: "What does \"duck\" mean?", options: ["con gà", "con vịt", "con lợn", "con bò"], correct_index: 1, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"duck\" có nghĩa là con vịt." },
  { id: 12, content: "What does \"frog\" mean?", options: ["con cú", "con cáo", "con ếch", "con sói"], correct_index: 2, type: "mcq", topic: "animals", level: 0, explanation_vi: "\"frog\" có nghĩa là con ếch." },

  { id: 13, content: "What does \"rice\" mean?", options: ["cơm", "sữa", "bánh mì", "trứng"], correct_index: 0, type: "mcq", topic: "food", level: 0, explanation_vi: "\"rice\" có nghĩa là cơm." },
  { id: 14, content: "What does \"milk\" mean?", options: ["nước", "sữa", "trà", "súp"], correct_index: 1, type: "mcq", topic: "food", level: 0, explanation_vi: "\"milk\" có nghĩa là sữa." },
  { id: 15, content: "What does \"bread\" mean?", options: ["thịt", "mì", "bánh mì", "phô mai"], correct_index: 2, type: "mcq", topic: "food", level: 0, explanation_vi: "\"bread\" có nghĩa là bánh mì." },
  { id: 16, content: "What does \"egg\" mean?", options: ["trứng", "kẹo", "mật ong", "ngô"], correct_index: 0, type: "mcq", topic: "food", level: 0, explanation_vi: "\"egg\" có nghĩa là trứng." },
  { id: 17, content: "What does \"cake\" mean?", options: ["mứt", "bánh ngọt", "kem", "trà"], correct_index: 1, type: "mcq", topic: "food", level: 0, explanation_vi: "\"cake\" có nghĩa là bánh ngọt." },
  { id: 18, content: "What does \"water\" mean?", options: ["súp", "thịt", "nước", "mì"], correct_index: 2, type: "mcq", topic: "food", level: 0, explanation_vi: "\"water\" có nghĩa là nước." },
  { id: 19, content: "What does \"candy\" mean?", options: ["kẹo", "phô mai", "ngô", "bánh quy"], correct_index: 0, type: "mcq", topic: "food", level: 0, explanation_vi: "\"candy\" có nghĩa là kẹo." },
  { id: 20, content: "What does \"ice cream\" mean?", options: ["trà", "kem", "nước ép", "mật ong"], correct_index: 1, type: "mcq", topic: "food", level: 0, explanation_vi: "\"ice cream\" có nghĩa là kem." },

  { id: 21, content: "What does \"mother\" mean?", options: ["mẹ", "bố", "bà", "chị gái"], correct_index: 0, type: "mcq", topic: "family", level: 0, explanation_vi: "\"mother\" có nghĩa là mẹ." },
  { id: 22, content: "What does \"father\" mean?", options: ["ông", "bố", "chú", "anh trai"], correct_index: 1, type: "mcq", topic: "family", level: 0, explanation_vi: "\"father\" có nghĩa là bố." },
  { id: 23, content: "What does \"sister\" mean?", options: ["em bé", "cô", "chị gái", "bạn"], correct_index: 2, type: "mcq", topic: "family", level: 0, explanation_vi: "\"sister\" có nghĩa là chị gái." },
  { id: 24, content: "What does \"baby\" mean?", options: ["em bé", "ông", "con gái", "cậu bé"], correct_index: 0, type: "mcq", topic: "family", level: 0, explanation_vi: "\"baby\" có nghĩa là em bé." },
  { id: 25, content: "What does \"grandma\" mean?", options: ["mẹ", "bà", "cô", "chị gái"], correct_index: 1, type: "mcq", topic: "family", level: 0, explanation_vi: "\"grandma\" có nghĩa là bà." },
  { id: 26, content: "What does \"brother\" mean?", options: ["bố", "ông", "anh trai", "chú"], correct_index: 2, type: "mcq", topic: "family", level: 0, explanation_vi: "\"brother\" có nghĩa là anh trai." },
  { id: 27, content: "What does \"family\" mean?", options: ["gia đình", "bạn", "cô bé", "cậu bé"], correct_index: 0, type: "mcq", topic: "family", level: 0, explanation_vi: "\"family\" có nghĩa là gia đình." },

  { id: 28, content: "What does \"head\" mean?", options: ["đầu", "mắt", "tai", "mũi"], correct_index: 0, type: "mcq", topic: "body", level: 0, explanation_vi: "\"head\" có nghĩa là đầu." },
  { id: 29, content: "What does \"eye\" mean?", options: ["tai", "mắt", "mũi", "miệng"], correct_index: 1, type: "mcq", topic: "body", level: 0, explanation_vi: "\"eye\" có nghĩa là mắt." },
  { id: 30, content: "What does \"hand\" mean?", options: ["chân", "tóc", "bàn tay", "răng"], correct_index: 2, type: "mcq", topic: "body", level: 0, explanation_vi: "\"hand\" có nghĩa là bàn tay." },
  { id: 31, content: "What does \"nose\" mean?", options: ["mũi", "tai", "miệng", "mắt"], correct_index: 0, type: "mcq", topic: "body", level: 0, explanation_vi: "\"nose\" có nghĩa là mũi." },
  { id: 32, content: "What does \"mouth\" mean?", options: ["tóc", "miệng", "tay", "chân"], correct_index: 1, type: "mcq", topic: "body", level: 0, explanation_vi: "\"mouth\" có nghĩa là miệng." },
  { id: 33, content: "What does \"foot\" mean?", options: ["cánh tay", "đầu", "bàn chân", "tóc"], correct_index: 2, type: "mcq", topic: "body", level: 0, explanation_vi: "\"foot\" có nghĩa là bàn chân." },
  { id: 34, content: "What does \"ear\" mean?", options: ["tai", "mắt", "mũi", "miệng"], correct_index: 0, type: "mcq", topic: "body", level: 0, explanation_vi: "\"ear\" có nghĩa là tai." },

  { id: 35, content: "What does \"red\" mean?", options: ["đỏ", "xanh dương", "vàng", "đen"], correct_index: 0, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"red\" có nghĩa là đỏ." },
  { id: 36, content: "What does \"blue\" mean?", options: ["trắng", "xanh dương", "hồng", "nâu"], correct_index: 1, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"blue\" có nghĩa là xanh dương." },
  { id: 37, content: "What does \"green\" mean?", options: ["tím", "cam", "xanh lá", "xám"], correct_index: 2, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"green\" có nghĩa là xanh lá." },
  { id: 38, content: "What does \"yellow\" mean?", options: ["vàng", "đen", "trắng", "hồng"], correct_index: 0, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"yellow\" có nghĩa là vàng." },
  { id: 39, content: "What does \"black\" mean?", options: ["đỏ", "đen", "cam", "xanh lá"], correct_index: 1, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"black\" có nghĩa là đen." },
  { id: 40, content: "What does \"pink\" mean?", options: ["nâu", "tím", "hồng", "bạc"], correct_index: 2, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"pink\" có nghĩa là hồng." },
  { id: 41, content: "What does \"white\" mean?", options: ["trắng", "đen", "vàng", "xanh"], correct_index: 0, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"white\" có nghĩa là trắng." },

  { id: 42, content: "What does \"ball\" mean?", options: ["quả bóng", "búp bê", "rô bốt", "cái diều"], correct_index: 0, type: "mcq", topic: "toys", level: 0, explanation_vi: "\"ball\" có nghĩa là quả bóng." },
  { id: 43, content: "What does \"doll\" mean?", options: ["rô bốt", "búp bê", "trống", "tàu"], correct_index: 1, type: "mcq", topic: "toys", level: 0, explanation_vi: "\"doll\" có nghĩa là búp bê." },
  { id: 44, content: "What does \"robot\" mean?", options: ["bóng bay", "gấu bông", "rô bốt", "khối xếp"], correct_index: 2, type: "mcq", topic: "toys", level: 0, explanation_vi: "\"robot\" có nghĩa là rô bốt." },
  { id: 45, content: "What does \"kite\" mean?", options: ["cái diều", "quả bóng", "cái trống", "búp bê"], correct_index: 0, type: "mcq", topic: "toys", level: 0, explanation_vi: "\"kite\" có nghĩa là cái diều." },

  { id: 46, content: "What does \"circle\" mean?", options: ["hình tròn", "hình vuông", "hình tam giác", "ngôi sao"], correct_index: 0, type: "mcq", topic: "shapes", level: 0, explanation_vi: "\"circle\" có nghĩa là hình tròn." },
  { id: 47, content: "What does \"square\" mean?", options: ["hình tròn", "hình vuông", "hình thoi", "đường thẳng"], correct_index: 1, type: "mcq", topic: "shapes", level: 0, explanation_vi: "\"square\" có nghĩa là hình vuông." },
  { id: 48, content: "What does \"star\" mean?", options: ["hình tròn", "hình vuông", "ngôi sao", "chấm tròn"], correct_index: 2, type: "mcq", topic: "shapes", level: 0, explanation_vi: "\"star\" có nghĩa là ngôi sao." },
  { id: 49, content: "What does \"triangle\" mean?", options: ["hình tam giác", "hình tròn", "hình vuông", "hình thoi"], correct_index: 0, type: "mcq", topic: "shapes", level: 0, explanation_vi: "\"triangle\" có nghĩa là hình tam giác." },

  { id: 50, content: "What does \"one\" mean?", options: ["số một", "số hai", "số ba", "số bốn"], correct_index: 0, type: "mcq", topic: "numbers", level: 0, explanation_vi: "\"one\" có nghĩa là số một." },
  { id: 51, content: "What does \"two\" mean?", options: ["số một", "số hai", "số ba", "số năm"], correct_index: 1, type: "mcq", topic: "numbers", level: 0, explanation_vi: "\"two\" có nghĩa là số hai." },
  { id: 52, content: "What does \"five\" mean?", options: ["số ba", "số bốn", "số năm", "số sáu"], correct_index: 2, type: "mcq", topic: "numbers", level: 0, explanation_vi: "\"five\" có nghĩa là số năm." },
  { id: 53, content: "What does \"ten\" mean?", options: ["số mười", "số chín", "số tám", "số bảy"], correct_index: 0, type: "mcq", topic: "numbers", level: 0, explanation_vi: "\"ten\" có nghĩa là số mười." },
  { id: 54, content: "What does \"three\" mean?", options: ["số một", "số hai", "số ba", "số bốn"], correct_index: 2, type: "mcq", topic: "numbers", level: 0, explanation_vi: "\"three\" có nghĩa là số ba." },
];

export const stories: Story[] = [
  { title: "My Pet Dog", title_vi: "Chú Chó Của Em", level: 0, unlock_level: 0, panels: [
    { en: "I have a dog.", vi: "Em có một con chó.", emoji: "🐶" },
    { en: "My dog is white.", vi: "Chó của em màu trắng.", emoji: "🐕" },
    { en: "The dog can run.", vi: "Con chó biết chạy.", emoji: "🏃" },
    { en: "The dog is happy.", vi: "Con chó đang vui.", emoji: "😊" },
    { en: "I love my dog.", vi: "Em yêu con chó.", emoji: "❤️" },
  ], questions: [
    { content: "What pet?", options: ["Cat", "Dog", "Bird", "Fish"], correct_index: 1 },
    { content: "Dog color?", options: ["Black", "Brown", "White", "Yellow"], correct_index: 2 },
    { content: "How does it feel?", options: ["Sad", "Angry", "Happy", "Tired"], correct_index: 2 },
  ] },
  { title: "Red Apple", title_vi: "Quả Táo Đỏ", level: 0, unlock_level: 0, panels: [
    { en: "This is an apple.", vi: "Đây là quả táo.", emoji: "🍎" },
    { en: "The apple is red.", vi: "Quả táo màu đỏ.", emoji: "🔴" },
    { en: "I eat the apple.", vi: "Em ăn quả táo.", emoji: "😋" },
    { en: "It is yummy!", vi: "Nó ngon quá!", emoji: "⭐" },
  ], questions: [
    { content: "What fruit?", options: ["Banana", "Apple", "Orange", "Grape"], correct_index: 1 },
    { content: "Apple color?", options: ["Green", "Yellow", "Red", "Blue"], correct_index: 2 },
    { content: "Taste?", options: ["Sour", "Yummy", "Bitter", "Bad"], correct_index: 1 },
  ] },
  { title: "Count With Me", title_vi: "Đếm Cùng Em", level: 0, unlock_level: 0, panels: [
    { en: "I see one cat.", vi: "Em thấy một con mèo.", emoji: "1️⃣" },
    { en: "I see two birds.", vi: "Em thấy hai con chim.", emoji: "2️⃣" },
    { en: "I see three fish.", vi: "Em thấy ba con cá.", emoji: "3️⃣" },
    { en: "I can count!", vi: "Em biết đếm rồi!", emoji: "🎉" },
  ], questions: [
    { content: "How many cats?", options: ["One", "Two", "Three", "Four"], correct_index: 0 },
    { content: "How many birds?", options: ["One", "Two", "Three", "Five"], correct_index: 1 },
    { content: "How many fish?", options: ["One", "Two", "Three", "Ten"], correct_index: 2 },
  ] },
];
