import type { Question, Story, VocabWord } from "../types";
import { TOPICS } from "../types";

export const topics: string[] = [...TOPICS];

export const vocabulary: VocabWord[] = [
  { id: 1, word: "run", meaning_vi: "chạy", emoji: "🏃", topic: "actions", level: 1, example_en: "I can run.", example_vi: "Em chạy.", part_of_speech: "verb" },
  { id: 2, word: "walk", meaning_vi: "đi bộ", emoji: "🚶", topic: "actions", level: 1, example_en: "Let us walk.", example_vi: "Đi bộ nhé.", part_of_speech: "verb" },
  { id: 3, word: "jump", meaning_vi: "nhảy", emoji: "🤸", topic: "actions", level: 1, example_en: "Rabbit jumps.", example_vi: "Thỏ nhảy.", part_of_speech: "verb" },
  { id: 4, word: "eat", meaning_vi: "ăn", emoji: "🍽️", topic: "actions", level: 1, example_en: "We eat lunch.", example_vi: "Chúng em ăn.", part_of_speech: "verb" },
  { id: 5, word: "drink", meaning_vi: "uống", emoji: "🥤", topic: "actions", level: 2, example_en: "Drink water.", example_vi: "Uống nước.", part_of_speech: "verb" },
  { id: 6, word: "sleep", meaning_vi: "ngủ", emoji: "😴", topic: "actions", level: 2, example_en: "Baby sleeps.", example_vi: "Em bé ngủ.", part_of_speech: "verb" },
  { id: 7, word: "read", meaning_vi: "đọc", emoji: "📖", topic: "actions", level: 2, example_en: "I read books.", example_vi: "Em đọc sách.", part_of_speech: "verb" },
  { id: 8, word: "write", meaning_vi: "viết", emoji: "✍️", topic: "actions", level: 2, example_en: "Write a letter.", example_vi: "Viết thư.", part_of_speech: "verb" },
  { id: 9, word: "dog", meaning_vi: "con chó", emoji: "🐶", topic: "animals", level: 1, example_en: "The dog runs fast.", example_vi: "Con chó chạy nhanh.", part_of_speech: "noun" },
  { id: 10, word: "cat", meaning_vi: "con mèo", emoji: "🐱", topic: "animals", level: 1, example_en: "The cat sleeps.", example_vi: "Con mèo ngủ.", part_of_speech: "noun" },
  { id: 11, word: "fish", meaning_vi: "con cá", emoji: "🐟", topic: "animals", level: 1, example_en: "Fish swim.", example_vi: "Cá bơi.", part_of_speech: "noun" },
  { id: 12, word: "bird", meaning_vi: "con chim", emoji: "🐦", topic: "animals", level: 1, example_en: "Birds fly.", example_vi: "Chim bay.", part_of_speech: "noun" },
  { id: 13, word: "horse", meaning_vi: "con ngựa", emoji: "🐴", topic: "animals", level: 2, example_en: "The horse runs.", example_vi: "Con ngựa chạy.", part_of_speech: "noun" },
  { id: 14, word: "pig", meaning_vi: "con lợn", emoji: "🐷", topic: "animals", level: 2, example_en: "The pig is pink.", example_vi: "Con lợn hồng.", part_of_speech: "noun" },
  { id: 15, word: "cow", meaning_vi: "con bò", emoji: "🐮", topic: "animals", level: 2, example_en: "The cow eats grass.", example_vi: "Con bò ăn cỏ.", part_of_speech: "noun" },
  { id: 16, word: "duck", meaning_vi: "con vịt", emoji: "🦆", topic: "animals", level: 2, example_en: "Ducks swim.", example_vi: "Vịt bơi.", part_of_speech: "noun" },
  { id: 17, word: "head", meaning_vi: "đầu", emoji: "👤", topic: "body", level: 0, example_en: "Nod your head.", example_vi: "Gật đầu.", part_of_speech: "noun" },
  { id: 18, word: "eye", meaning_vi: "mắt", emoji: "👁️", topic: "body", level: 0, example_en: "Close your eyes.", example_vi: "Nhắm mắt.", part_of_speech: "noun" },
  { id: 19, word: "ear", meaning_vi: "tai", emoji: "👂", topic: "body", level: 0, example_en: "Listen with ears.", example_vi: "Nghe bằng tai.", part_of_speech: "noun" },
  { id: 20, word: "nose", meaning_vi: "mũi", emoji: "👃", topic: "body", level: 1, example_en: "Touch your nose.", example_vi: "Sờ mũi.", part_of_speech: "noun" },
  { id: 21, word: "mouth", meaning_vi: "miệng", emoji: "👄", topic: "body", level: 1, example_en: "Open your mouth.", example_vi: "Há miệng.", part_of_speech: "noun" },
  { id: 22, word: "hand", meaning_vi: "tay", emoji: "✋", topic: "body", level: 1, example_en: "Wash your hands.", example_vi: "Rửa tay.", part_of_speech: "noun" },
  { id: 23, word: "red", meaning_vi: "đỏ", emoji: "🔴", topic: "colors", level: 0, example_en: "Apple is red.", example_vi: "Táo đỏ.", part_of_speech: "adj" },
  { id: 24, word: "blue", meaning_vi: "xanh dương", emoji: "🔵", topic: "colors", level: 0, example_en: "Sky is blue.", example_vi: "Trời xanh.", part_of_speech: "adj" },
  { id: 25, word: "green", meaning_vi: "xanh lá", emoji: "🟢", topic: "colors", level: 0, example_en: "Grass is green.", example_vi: "Cỏ xanh.", part_of_speech: "adj" },
  { id: 26, word: "yellow", meaning_vi: "vàng", emoji: "🟡", topic: "colors", level: 1, example_en: "Sun is yellow.", example_vi: "Mặt trời vàng.", part_of_speech: "adj" },
  { id: 27, word: "white", meaning_vi: "trắng", emoji: "⚪", topic: "colors", level: 1, example_en: "Snow is white.", example_vi: "Tuyết trắng.", part_of_speech: "adj" },
  { id: 28, word: "black", meaning_vi: "đen", emoji: "⚫", topic: "colors", level: 1, example_en: "Night is black.", example_vi: "Đêm đen.", part_of_speech: "adj" },
  { id: 29, word: "mother", meaning_vi: "mẹ", emoji: "👩", topic: "family", level: 0, example_en: "Mother is kind.", example_vi: "Mẹ hiền.", part_of_speech: "noun" },
  { id: 30, word: "father", meaning_vi: "bố", emoji: "👨", topic: "family", level: 0, example_en: "Father is tall.", example_vi: "Bố cao.", part_of_speech: "noun" },
  { id: 31, word: "sister", meaning_vi: "chị gái", emoji: "👧", topic: "family", level: 0, example_en: "Sister is young.", example_vi: "Chị trẻ.", part_of_speech: "noun" },
  { id: 32, word: "brother", meaning_vi: "anh trai", emoji: "👦", topic: "family", level: 1, example_en: "Brother runs.", example_vi: "Anh trai chạy.", part_of_speech: "noun" },
  { id: 33, word: "baby", meaning_vi: "em bé", emoji: "👶", topic: "family", level: 1, example_en: "Baby laughs.", example_vi: "Em bé cười.", part_of_speech: "noun" },
  { id: 34, word: "grandma", meaning_vi: "bà", emoji: "👵", topic: "family", level: 1, example_en: "Grandma cooks.", example_vi: "Bà nấu ăn.", part_of_speech: "noun" },
  { id: 35, word: "rice", meaning_vi: "cơm", emoji: "🍚", topic: "food", level: 0, example_en: "I eat rice.", example_vi: "Em ăn cơm.", part_of_speech: "noun" },
  { id: 36, word: "bread", meaning_vi: "bánh mì", emoji: "🍞", topic: "food", level: 0, example_en: "Bread is tasty.", example_vi: "Bánh mì ngon.", part_of_speech: "noun" },
  { id: 37, word: "milk", meaning_vi: "sữa", emoji: "🥛", topic: "food", level: 0, example_en: "I drink milk.", example_vi: "Em uống sữa.", part_of_speech: "noun" },
  { id: 38, word: "egg", meaning_vi: "trứng", emoji: "🥚", topic: "food", level: 1, example_en: "Egg is round.", example_vi: "Trứng tròn.", part_of_speech: "noun" },
  { id: 39, word: "cake", meaning_vi: "bánh", emoji: "🎂", topic: "food", level: 1, example_en: "Cake is sweet.", example_vi: "Bánh ngọt.", part_of_speech: "noun" },
  { id: 40, word: "candy", meaning_vi: "kẹo", emoji: "🍬", topic: "food", level: 1, example_en: "Candy is sweet.", example_vi: "Kẹo ngọt.", part_of_speech: "noun" },
  { id: 41, word: "apple", meaning_vi: "táo", emoji: "🍎", topic: "fruits", level: 0, example_en: "Apple is red.", example_vi: "Táo đỏ.", part_of_speech: "noun" },
  { id: 42, word: "banana", meaning_vi: "chuối", emoji: "🍌", topic: "fruits", level: 0, example_en: "Banana is yellow.", example_vi: "Chuối vàng.", part_of_speech: "noun" },
  { id: 43, word: "orange", meaning_vi: "cam", emoji: "🍊", topic: "fruits", level: 0, example_en: "Orange is round.", example_vi: "Cam tròn.", part_of_speech: "noun" },
  { id: 44, word: "grape", meaning_vi: "nho", emoji: "🍇", topic: "fruits", level: 1, example_en: "Grapes are small.", example_vi: "Nho nhỏ.", part_of_speech: "noun" },
  { id: 45, word: "mango", meaning_vi: "xoài", emoji: "🥭", topic: "fruits", level: 1, example_en: "Mango is sweet.", example_vi: "Xoài ngọt.", part_of_speech: "noun" },
  { id: 46, word: "doctor", meaning_vi: "bác sĩ", emoji: "👨‍⚕️", topic: "jobs", level: 1, example_en: "Doctor helps.", example_vi: "Bác sĩ giúp người.", part_of_speech: "noun" },
  { id: 47, word: "pilot", meaning_vi: "phi công", emoji: "🧑‍✈️", topic: "jobs", level: 1, example_en: "Pilot flies.", example_vi: "Phi công lái bay.", part_of_speech: "noun" },
  { id: 48, word: "nurse", meaning_vi: "y tá", emoji: "👩‍⚕️", topic: "jobs", level: 1, example_en: "Nurse is kind.", example_vi: "Y tá tốt.", part_of_speech: "noun" },
  { id: 49, word: "cook", meaning_vi: "đầu bếp", emoji: "👨‍🍳", topic: "jobs", level: 1, example_en: "Cook makes food.", example_vi: "Đầu bếp nấu.", part_of_speech: "noun" },
  { id: 50, word: "farmer", meaning_vi: "nông dân", emoji: "👨‍🌾", topic: "jobs", level: 2, example_en: "Farmer grows rice.", example_vi: "Nông dân trồng lúa.", part_of_speech: "noun" },
  { id: 51, word: "tree", meaning_vi: "cây", emoji: "🌳", topic: "nature", level: 1, example_en: "Tree is tall.", example_vi: "Cây cao.", part_of_speech: "noun" },
  { id: 52, word: "flower", meaning_vi: "hoa", emoji: "🌸", topic: "nature", level: 1, example_en: "Flower is pretty.", example_vi: "Hoa đẹp.", part_of_speech: "noun" },
  { id: 53, word: "sun", meaning_vi: "mặt trời", emoji: "☀️", topic: "nature", level: 1, example_en: "Sun is bright.", example_vi: "Mặt trời sáng.", part_of_speech: "noun" },
  { id: 54, word: "moon", meaning_vi: "mặt trăng", emoji: "🌙", topic: "nature", level: 1, example_en: "Moon is round.", example_vi: "Trăng tròn.", part_of_speech: "noun" },
  { id: 55, word: "river", meaning_vi: "sông", emoji: "🌊", topic: "nature", level: 2, example_en: "River is long.", example_vi: "Sông dài.", part_of_speech: "noun" },
  { id: 56, word: "sea", meaning_vi: "biển", emoji: "🌊", topic: "nature", level: 2, example_en: "Sea is blue.", example_vi: "Biển xanh.", part_of_speech: "noun" },
  { id: 57, word: "book", meaning_vi: "sách", emoji: "📚", topic: "school", level: 1, example_en: "I have a book.", example_vi: "Em có sách.", part_of_speech: "noun" },
  { id: 58, word: "pen", meaning_vi: "bút", emoji: "🖊️", topic: "school", level: 1, example_en: "This is my pen.", example_vi: "Bút của em.", part_of_speech: "noun" },
  { id: 59, word: "teacher", meaning_vi: "cô giáo", emoji: "👩‍🏫", topic: "school", level: 1, example_en: "Teacher is nice.", example_vi: "Cô giáo tốt.", part_of_speech: "noun" },
  { id: 60, word: "pencil", meaning_vi: "bút chì", emoji: "✏️", topic: "school", level: 1, example_en: "Draw with pencil.", example_vi: "Vẽ bằng bút chì.", part_of_speech: "noun" },
  { id: 61, word: "bag", meaning_vi: "cặp", emoji: "🎒", topic: "school", level: 2, example_en: "My bag is new.", example_vi: "Cặp em mới.", part_of_speech: "noun" },
  { id: 62, word: "ball", meaning_vi: "bóng", emoji: "⚽", topic: "toys", level: 0, example_en: "I play ball.", example_vi: "Em chơi bóng.", part_of_speech: "noun" },
  { id: 63, word: "doll", meaning_vi: "búp bê", emoji: "🎎", topic: "toys", level: 0, example_en: "Doll is pretty.", example_vi: "Búp bê đẹp.", part_of_speech: "noun" },
  { id: 64, word: "robot", meaning_vi: "rô bốt", emoji: "🤖", topic: "toys", level: 0, example_en: "Robot talks.", example_vi: "Rô bốt nói.", part_of_speech: "noun" },
  { id: 65, word: "kite", meaning_vi: "diều", emoji: "🪁", topic: "toys", level: 1, example_en: "Fly a kite.", example_vi: "Thả diều.", part_of_speech: "noun" },
  { id: 66, word: "puzzle", meaning_vi: "xếp hình", emoji: "🧩", topic: "toys", level: 1, example_en: "Solve puzzle.", example_vi: "Xếp hình.", part_of_speech: "noun" },
  { id: 67, word: "sunny", meaning_vi: "nắng", emoji: "☀️", topic: "weather", level: 1, example_en: "Today is sunny.", example_vi: "Hôm nay nắng.", part_of_speech: "adj" },
  { id: 68, word: "rainy", meaning_vi: "mưa", emoji: "🌧️", topic: "weather", level: 1, example_en: "It is rainy.", example_vi: "Trời mưa.", part_of_speech: "adj" },
  { id: 69, word: "cloudy", meaning_vi: "mây", emoji: "☁️", topic: "weather", level: 1, example_en: "Sky is cloudy.", example_vi: "Trời có mây.", part_of_speech: "adj" },
  { id: 70, word: "windy", meaning_vi: "gió", emoji: "💨", topic: "weather", level: 1, example_en: "It is windy.", example_vi: "Trời có gió.", part_of_speech: "adj" },
  { id: 71, word: "hot", meaning_vi: "nóng", emoji: "🥵", topic: "weather", level: 2, example_en: "Summer is hot.", example_vi: "Mùa hè nóng.", part_of_speech: "adj" },
  { id: 72, word: "cold", meaning_vi: "lạnh", emoji: "🥶", topic: "weather", level: 2, example_en: "Winter is cold.", example_vi: "Mùa đông lạnh.", part_of_speech: "adj" },
];

export const questions: Question[] = [
  { id: 1, content: "What does \"run\" mean?", options: ["chạy", "mẹ", "con chim", "gió"], correct_index: 0, type: "mcq", topic: "actions", level: 1, explanation_vi: "\"run\" có nghĩa là chạy." },
  { id: 2, content: "What does \"jump\" mean?", options: ["nhảy", "tay", "tai", "anh trai"], correct_index: 0, type: "mcq", topic: "actions", level: 1, explanation_vi: "\"jump\" có nghĩa là nhảy." },
  { id: 3, content: "What does \"drink\" mean?", options: ["uống", "đen", "diều", "vàng"], correct_index: 0, type: "mcq", topic: "actions", level: 2, explanation_vi: "\"drink\" có nghĩa là uống." },
  { id: 4, content: "What does \"read\" mean?", options: ["đọc", "nông dân", "con ngựa", "con chim"], correct_index: 0, type: "mcq", topic: "actions", level: 2, explanation_vi: "\"read\" có nghĩa là đọc." },
  { id: 5, content: "What does \"dog\" mean?", options: ["con chó", "trắng", "tai", "miệng"], correct_index: 0, type: "mcq", topic: "animals", level: 1, explanation_vi: "\"dog\" có nghĩa là con chó." },
  { id: 6, content: "What does \"fish\" mean?", options: ["con cá", "nho", "con ngựa", "đầu"], correct_index: 0, type: "mcq", topic: "animals", level: 1, explanation_vi: "\"fish\" có nghĩa là con cá." },
  { id: 7, content: "What does \"horse\" mean?", options: ["con ngựa", "diều", "đầu bếp", "mũi"], correct_index: 0, type: "mcq", topic: "animals", level: 2, explanation_vi: "\"horse\" có nghĩa là con ngựa." },
  { id: 8, content: "What does \"cow\" mean?", options: ["con bò", "mặt trời", "nóng", "con chó"], correct_index: 0, type: "mcq", topic: "animals", level: 2, explanation_vi: "\"cow\" có nghĩa là con bò." },
  { id: 9, content: "What does \"head\" mean?", options: ["đầu", "cơm", "nông dân", "đọc"], correct_index: 0, type: "mcq", topic: "body", level: 0, explanation_vi: "\"head\" có nghĩa là đầu." },
  { id: 10, content: "What does \"ear\" mean?", options: ["tai", "nóng", "bà", "mắt"], correct_index: 0, type: "mcq", topic: "body", level: 0, explanation_vi: "\"ear\" có nghĩa là tai." },
  { id: 11, content: "What does \"mouth\" mean?", options: ["miệng", "đọc", "đen", "vàng"], correct_index: 0, type: "mcq", topic: "body", level: 1, explanation_vi: "\"mouth\" có nghĩa là miệng." },
  { id: 12, content: "What does \"red\" mean?", options: ["đỏ", "bút chì", "đen", "sách"], correct_index: 0, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"red\" có nghĩa là đỏ." },
  { id: 13, content: "What does \"green\" mean?", options: ["xanh lá", "viết", "mây", "con lợn"], correct_index: 0, type: "mcq", topic: "colors", level: 0, explanation_vi: "\"green\" có nghĩa là xanh lá." },
  { id: 14, content: "What does \"white\" mean?", options: ["trắng", "mặt trăng", "rô bốt", "chị gái"], correct_index: 0, type: "mcq", topic: "colors", level: 1, explanation_vi: "\"white\" có nghĩa là trắng." },
  { id: 15, content: "What does \"mother\" mean?", options: ["mẹ", "bút chì", "xanh lá", "xếp hình"], correct_index: 0, type: "mcq", topic: "family", level: 0, explanation_vi: "\"mother\" có nghĩa là mẹ." },
  { id: 16, content: "What does \"sister\" mean?", options: ["chị gái", "chạy", "bút", "kẹo"], correct_index: 0, type: "mcq", topic: "family", level: 0, explanation_vi: "\"sister\" có nghĩa là chị gái." },
  { id: 17, content: "What does \"baby\" mean?", options: ["em bé", "đỏ", "con lợn", "miệng"], correct_index: 0, type: "mcq", topic: "family", level: 1, explanation_vi: "\"baby\" có nghĩa là em bé." },
  { id: 18, content: "What does \"rice\" mean?", options: ["cơm", "chạy", "xanh lá", "miệng"], correct_index: 0, type: "mcq", topic: "food", level: 0, explanation_vi: "\"rice\" có nghĩa là cơm." },
  { id: 19, content: "What does \"milk\" mean?", options: ["sữa", "trắng", "bút chì", "nóng"], correct_index: 0, type: "mcq", topic: "food", level: 0, explanation_vi: "\"milk\" có nghĩa là sữa." },
  { id: 20, content: "What does \"cake\" mean?", options: ["bánh", "mặt trăng", "bút", "cơm"], correct_index: 0, type: "mcq", topic: "food", level: 1, explanation_vi: "\"cake\" có nghĩa là bánh." },
  { id: 21, content: "What does \"apple\" mean?", options: ["táo", "bút", "viết", "đầu"], correct_index: 0, type: "mcq", topic: "fruits", level: 0, explanation_vi: "\"apple\" có nghĩa là táo." },
  { id: 22, content: "What does \"orange\" mean?", options: ["cam", "mây", "xanh dương", "bánh mì"], correct_index: 0, type: "mcq", topic: "fruits", level: 0, explanation_vi: "\"orange\" có nghĩa là cam." },
  { id: 23, content: "What does \"mango\" mean?", options: ["xoài", "rô bốt", "tay", "cơm"], correct_index: 0, type: "mcq", topic: "fruits", level: 1, explanation_vi: "\"mango\" có nghĩa là xoài." },
  { id: 24, content: "What does \"doctor\" mean?", options: ["bác sĩ", "sông", "cô giáo", "mây"], correct_index: 0, type: "mcq", topic: "jobs", level: 1, explanation_vi: "\"doctor\" có nghĩa là bác sĩ." },
  { id: 25, content: "What does \"nurse\" mean?", options: ["y tá", "tai", "ăn", "con vịt"], correct_index: 0, type: "mcq", topic: "jobs", level: 1, explanation_vi: "\"nurse\" có nghĩa là y tá." },
  { id: 26, content: "What does \"farmer\" mean?", options: ["nông dân", "mũi", "con ngựa", "nhảy"], correct_index: 0, type: "mcq", topic: "jobs", level: 2, explanation_vi: "\"farmer\" có nghĩa là nông dân." },
  { id: 27, content: "What does \"tree\" mean?", options: ["cây", "bác sĩ", "mây", "đỏ"], correct_index: 0, type: "mcq", topic: "nature", level: 1, explanation_vi: "\"tree\" có nghĩa là cây." },
  { id: 28, content: "What does \"sun\" mean?", options: ["mặt trời", "mắt", "nhảy", "cam"], correct_index: 0, type: "mcq", topic: "nature", level: 1, explanation_vi: "\"sun\" có nghĩa là mặt trời." },
  { id: 29, content: "What does \"river\" mean?", options: ["sông", "cặp", "mặt trời", "em bé"], correct_index: 0, type: "mcq", topic: "nature", level: 2, explanation_vi: "\"river\" có nghĩa là sông." },
  { id: 30, content: "What does \"book\" mean?", options: ["sách", "mưa", "anh trai", "tay"], correct_index: 0, type: "mcq", topic: "school", level: 1, explanation_vi: "\"book\" có nghĩa là sách." },
  { id: 31, content: "What does \"teacher\" mean?", options: ["cô giáo", "rô bốt", "mưa", "nông dân"], correct_index: 0, type: "mcq", topic: "school", level: 1, explanation_vi: "\"teacher\" có nghĩa là cô giáo." },
  { id: 32, content: "What does \"bag\" mean?", options: ["cặp", "phi công", "sách", "tai"], correct_index: 0, type: "mcq", topic: "school", level: 2, explanation_vi: "\"bag\" có nghĩa là cặp." },
  { id: 33, content: "What does \"ball\" mean?", options: ["bóng", "anh trai", "nho", "chuối"], correct_index: 0, type: "mcq", topic: "toys", level: 0, explanation_vi: "\"ball\" có nghĩa là bóng." },
  { id: 34, content: "What does \"robot\" mean?", options: ["rô bốt", "vàng", "con bò", "mẹ"], correct_index: 0, type: "mcq", topic: "toys", level: 0, explanation_vi: "\"robot\" có nghĩa là rô bốt." },
  { id: 35, content: "What does \"puzzle\" mean?", options: ["xếp hình", "bà", "cơm", "đầu bếp"], correct_index: 0, type: "mcq", topic: "toys", level: 1, explanation_vi: "\"puzzle\" có nghĩa là xếp hình." },
  { id: 36, content: "What does \"sunny\" mean?", options: ["nắng", "đỏ", "cặp", "bút chì"], correct_index: 0, type: "mcq", topic: "weather", level: 1, explanation_vi: "\"sunny\" có nghĩa là nắng." },
  { id: 37, content: "What does \"cloudy\" mean?", options: ["mây", "sông", "búp bê", "nắng"], correct_index: 0, type: "mcq", topic: "weather", level: 1, explanation_vi: "\"cloudy\" có nghĩa là mây." },
  { id: 38, content: "What does \"hot\" mean?", options: ["nóng", "xếp hình", "con mèo", "mẹ"], correct_index: 0, type: "mcq", topic: "weather", level: 2, explanation_vi: "\"hot\" có nghĩa là nóng." },
];

export const stories: Story[] = [
{ title: "My Pet Dog", title_vi: "Chú Chó Của Em", level: 0, unlock_level: 0, panels: [
    { en: "I have a dog.", vi: "Em có một con chó.", emoji: "🐶" },
    { en: "My dog is white.", vi: "Chó của em màu trắng.", emoji: "🐕" },
    { en: "The dog is happy.", vi: "Con chó đang vui.", emoji: "😊" },
    { en: "I love my dog.", vi: "Em yêu con chó.", emoji: "❤️" },
  ], questions: [
    { content: "What pet?", options: ["Cat", "Dog", "Bird", "Fish"], correct_index: 1 },
    { content: "Dog color?", options: ["Black", "Brown", "White", "Yellow"], correct_index: 2 },
    { content: "How feels?", options: ["Sad", "Angry", "Happy", "Tired"], correct_index: 2 },
  ] },
{ title: "Red Apple", title_vi: "Quả Táo Đỏ", level: 0, unlock_level: 0, panels: [
    { en: "This is an apple.", vi: "Đây là quả táo.", emoji: "🍎" },
    { en: "The apple is red.", vi: "Quả táo màu đỏ.", emoji: "🔴" },
    { en: "I eat the apple.", vi: "Em ăn quả táo.", emoji: "😋" },
    { en: "It is yummy!", vi: "Nó ngon quá!", emoji: "⭐" },
  ], questions: [
    { content: "What fruit?", options: ["Banana", "Apple", "Orange", "Grape"], correct_index: 1 },
    { content: "Apple color?", options: ["Green", "Yellow", "Red", "Blue"], correct_index: 2 },
    { content: "Taste?", options: ["Sour", "Yummy", "Bitter", "Bad"], correct_index: 1 },
  ] },
{ title: "The Cat and Fish", title_vi: "Mèo Và Cá", level: 1, unlock_level: 0, panels: [
    { en: "A cat is hungry.", vi: "Mèo đói.", emoji: "🐱" },
    { en: "Cat sees a fish.", vi: "Mèo thấy cá.", emoji: "🐟" },
    { en: "Fish swims away.", vi: "Cá bơi đi.", emoji: "🏊" },
    { en: "Bird shares food.", vi: "Chim chia sẻ.", emoji: "🐦" },
    { en: "Cat is happy.", vi: "Mèo vui.", emoji: "😊" },
  ], questions: [
    { content: "Who is hungry?", options: ["Dog", "Cat", "Bird", "Fish"], correct_index: 1 },
    { content: "Who shares food?", options: ["Dog", "Cat", "Bird", "Fish"], correct_index: 2 },
    { content: "Cat feels?", options: ["Sad", "Angry", "Happy", "Tired"], correct_index: 2 },
  ] },
{ title: "My School Day", title_vi: "Ngày Đi Học", level: 1, unlock_level: 0, panels: [
    { en: "I go to school.", vi: "Em đi học.", emoji: "🏫" },
    { en: "I have a new bag.", vi: "Em có cặp mới.", emoji: "🎒" },
    { en: "Teacher is nice.", vi: "Cô giáo tốt.", emoji: "👩‍🏫" },
    { en: "I make friends.", vi: "Em kết bạn.", emoji: "🤝" },
    { en: "School is fun!", vi: "Trường vui!", emoji: "🎉" },
  ], questions: [
    { content: "Where?", options: ["Park", "School", "Store", "Home"], correct_index: 1 },
    { content: "Who is nice?", options: ["Friend", "Teacher", "Mom", "Dad"], correct_index: 1 },
    { content: "How feels?", options: ["Sad", "Bored", "Happy", "Scared"], correct_index: 2 },
  ] },
{ title: "Weather Changes", title_vi: "Thời Tiết", level: 2, unlock_level: 1, panels: [
    { en: "Sunny morning.", vi: "Sáng nắng.", emoji: "☀️" },
    { en: "Clouds appear.", vi: "Mây xuất hiện.", emoji: "☁️" },
    { en: "Wind blows.", vi: "Gió thổi.", emoji: "💨" },
    { en: "Rain starts.", vi: "Mưa bắt đầu.", emoji: "🌧️" },
    { en: "Children run home.", vi: "Các bạn chạy về.", emoji: "🏃" },
    { en: "Drink warm milk.", vi: "Uống sữa ấm.", emoji: "🥛" },
  ], questions: [
    { content: "Morning weather?", options: ["Rainy", "Sunny", "Cloudy", "Snowy"], correct_index: 1 },
    { content: "What do they drink?", options: ["Water", "Juice", "Milk", "Tea"], correct_index: 2 },
    { content: "How do they feel?", options: ["Cold", "Warm", "Scared", "Angry"], correct_index: 1 },
  ] },
{ title: "Helping Grandma", title_vi: "Giúp Bà", level: 2, unlock_level: 1, panels: [
    { en: "Tom visits grandma.", vi: "Tom thăm bà.", emoji: "👦" },
    { en: "Grandma in garden.", vi: "Bà trong vườn.", emoji: "👩‍🌾" },
    { en: "Plants flowers.", vi: "Trồng hoa.", emoji: "🌷" },
    { en: "Tom helps dig.", vi: "Tom giúp.", emoji: "⛏️" },
    { en: "Grandma is happy.", vi: "Bà vui.", emoji: "😊" },
    { en: "Tom feels proud.", vi: "Tom tự hào.", emoji: "💪" },
  ], questions: [
    { content: "Who does Tom visit?", options: ["Friend", "Grandma", "Teacher", "Aunt"], correct_index: 1 },
    { content: "What is grandma doing?", options: ["Cooking", "Planting", "Reading", "Sleeping"], correct_index: 1 },
    { content: "How does Tom feel?", options: ["Sad", "Tired", "Proud", "Scared"], correct_index: 2 },
  ] },
];