import type { Story } from "../types";

export const libraryStories: Story[] = [
  {
    id: 1,
    title: "The Tortoise and the Hare",
    title_vi: "Rùa và Thỏ",
    panels: [
      { en: "A hare laughs at a tortoise for being slow.", vi: "Thỏ cười nhạo Rùa vì chậm chạp.", emoji: "🐇" },
      { en: '"You are the slowest animal I know!" says the hare.', vi: '"Cậu là con vật chậm nhất tôi biết!" Thỏ nói.', emoji: "😆" },
      { en: '"Let us race," says the tortoise calmly.', vi: '"Hãy thi chạy đi," Rùa bình thản nói.', emoji: "🐢" },
      { en: "The race begins. The hare runs fast, then stops to rest.", vi: "Cuộc đua bắt đầu. Thỏ chạy nhanh rồi dừng nghỉ.", emoji: "🏃‍♂️" },
      { en: '"I have plenty of time. I will take a nap," he thinks.', vi: '"Còn nhiều thời gian, ngủ một lát đã," nó nghĩ.', emoji: "😴" },
      { en: "The tortoise keeps walking, step by step, never stopping.", vi: "Rùa cứ bước, từng bước một, không ngừng nghỉ.", emoji: "🚶" },
      { en: "The hare wakes up and sees the tortoise near the finish line.", vi: "Thỏ thức dậy và thấy Rùa gần vạch đích.", emoji: "😱" },
      { en: "The tortoise wins the race. Slow and steady wins the race.", vi: "Rùa thắng cuộc đua. Chậm mà chắc sẽ chiến thắng.", emoji: "🏆" },
    ],
  },
  {
    id: 2,
    title: "The Boy Who Cried Wolf",
    title_vi: "Cậu Bé Chăn Cừu",
    panels: [
      { en: "A boy watches sheep near a village.", vi: "Một cậu bé trông cừu gần làng.", emoji: "🐑" },
      { en: "He feels bored and wants some excitement.", vi: "Cậu thấy chán và muốn chút náo nhiệt.", emoji: "😐" },
      { en: '"Wolf! Wolf!" he shouts. The villagers run to help.', vi: '"Sói! Sói!" cậu la lên. Dân làng chạy đến.', emoji: "🏃‍♂️" },
      { en: "There is no wolf. The boy laughs at them.", vi: "Không có sói. Cậu bé cười họ.", emoji: "😂" },
      { en: "The next day, he cries wolf again. The villagers come again, angry.", vi: "Hôm sau, cậu lại la sói. Dân làng lại đến, tức giận.", emoji: "😠" },
      { en: "Then a real wolf appears. The boy screams for help.", vi: "Rồi sói thật xuất hiện. Cậu bé la hét cầu cứu.", emoji: "🐺" },
      { en: "No one comes. The wolf eats all the sheep.", vi: "Không ai đến. Sói ăn hết đàn cừu.", emoji: "😭" },
      { en: "Nobody believes a liar, even when they tell the truth.", vi: "Không ai tin kẻ nói dối, dù họ có nói thật.", emoji: "💡" },
    ],
  },
  {
    id: 3,
    title: "The Lion and the Mouse",
    title_vi: "Sư Tử và Chuột Nhắt",
    panels: [
      { en: "A lion sleeps under a big tree.", vi: "Sư tử ngủ dưới gốc cây to.", emoji: "🦁" },
      { en: "A little mouse runs across his nose, waking him up.", vi: "Chuột nhắt chạy qua mũi sư tử, đánh thức nó dậy.", emoji: "🐭" },
      { en: '"How dare you!" the lion roars and catches the mouse.', vi: '"Sao dám chứ!" sư tử gầm lên và vồ chuột.', emoji: "😡" },
      { en: '"Please let me go! I might help you one day," the mouse squeaks.', vi: '"Làm ơn thả tôi! Một ngày nào đó tôi có thể giúp ngài," chuột kêu.', emoji: "🥺" },
      { en: '"You? Help me?" laughs the lion, but he lets the mouse go.', vi: '"Cậu? Giúp tôi?" sư tử cười, nhưng thả chuột.', emoji: "😏" },
      { en: "Days later, hunters trap the lion in a net.", vi: "Ít ngày sau, thợ săn bẫy sư tử trong lưới.", emoji: "🕸️" },
      { en: "The mouse hears the lion's roar and chews the net open.", vi: "Chuột nghe tiếng sư tử gầm, liền cắn đứt lưới.", emoji: "🦷" },
      { en: "Even small friends can be great helpers.", vi: "Ngay cả bạn nhỏ cũng có thể giúp ích lớn.", emoji: "🤝" },
    ],
  },
  {
    id: 4,
    title: "The Fox and the Grapes",
    title_vi: "Cáo và Nho",
    panels: [
      { en: "A fox walks through a forest on a hot day.", vi: "Cáo đi qua khu rừng trong ngày nóng.", emoji: "🦊" },
      { en: "He sees a bunch of grapes hanging high above.", vi: "Nó thấy chùm nho treo cao trên cao.", emoji: "🍇" },
      { en: '"Those grapes look juicy and sweet!" he thinks.', vi: '"Nho đó trông mọng nước và ngọt quá!" nó nghĩ.', emoji: "🤤" },
      { en: "He jumps and tries to reach the grapes, but they are too high.", vi: "Nó nhảy với tay nho, nhưng cao quá.", emoji: "🦘" },
      { en: "Again and again he jumps, but he cannot get them.", vi: "Hết lần này đến lần khác nó nhảy, nhưng không với tới.", emoji: "😫" },
      { en: "Finally, he gives up and walks away.", vi: "Cuối cùng, nó bỏ cuộc và bỏ đi.", emoji: "😤" },
      { en: '"Those grapes are probably sour anyway," he mutters.', vi: '"Chắc nho đó chua thôi," nó lẩm bẩm.', emoji: "🙄" },
      { en: "It is easy to hate what you cannot have.", vi: "Thật dễ để ghét thứ mình không thể có.", emoji: "💭" },
    ],
  },
  {
    id: 5,
    title: "The Ant and the Grasshopper",
    title_vi: "Kiến và Châu Chấu",
    panels: [
      { en: "Summer is warm and the sun shines brightly.", vi: "Mùa hè ấm áp và mặt trời chiếu sáng.", emoji: "☀️" },
      { en: "A grasshopper sings and dances all day long.", vi: "Châu chấu ca hát và nhảy múa suốt ngày.", emoji: "🦗" },
      { en: '"Come work with me before winter comes," says an ant.', vi: '"Đến làm việc với tôi trước khi mùa đông đến," kiến nói.', emoji: "🐜" },
      { en: '"Why work? There is plenty of food today!" laughs the grasshopper.', vi: '"Sao phải làm? Hôm nay còn nhiều thức ăn mà!" châu chấu cười.', emoji: "🎵" },
      { en: "The ant carries grain to her nest every day.", vi: "Kiến mang hạt lúa về tổ mỗi ngày.", emoji: "🏋️" },
      { en: "Winter comes. Snow covers the ground. Food is gone.", vi: "Mùa đông đến, tuyết phủ mặt đất, thức ăn không còn.", emoji: "❄️" },
      { en: "The grasshopper is cold and hungry. He begs the ant for food.", vi: "Châu chấu đói lạnh. Nó xin kiến chút thức ăn.", emoji: "🥶" },
      { en: "Work today so you can rest tomorrow.", vi: "Hãy làm việc hôm nay để ngày mai được nghỉ ngơi.", emoji: "💪" },
    ],
  },
];
