import type { Story } from "../types";

export const libraryStories: Story[] = [
  {
    id: 1,
    title: "The Tortoise and the Hare",
    title_vi: "Rùa và Thỏ",
    thumbnail: "🐢",
    color: "#F0FFF0",
    panels: [
      { en: "A hare laughs at a tortoise for being slow.", vi: "Thỏ cười nhạo Rùa vì chậm chạp.", emoji: "🐇" },
      { en: '"You are the slowest animal I know!" says the hare.', vi: '"Cậu là con vật chậm nhất tôi biết!" Thỏ nói.', emoji: "😆" },
      { en: '"Let us race," says the tortoise calmly.', vi: '"Hãy thi chạy đi," Rùa bình thản nói.', emoji: "🐢" },
      { en: "The race begins. The hare runs fast, then stops to rest.", vi: "Cuộc đua bắt đầu. Thỏ chạy nhanh rồi dừng nghỉ.", emoji: "🏃‍♂️" },
      { en: '"I have plenty of time. I will take a nap," he thinks.', vi: '"Còn nhiều thời gian, ngủ một lát đã," nó nghĩ.', emoji: "😴" },
      { en: "The tortoise keeps walking, step by step, never stopping.", vi: "Rùa cứ bước, từng bước một, không ngừng nghỉ.", emoji: "🚶" },
      { en: "The hare wakes up and sees the tortoise near the finish line.", vi: "Thỏ thức dậy và thấy Rùa gần vạch đích.", emoji: "😱" },
      { en: "The tortoise wins the race. Slow and steady wins the race.", vi: "Rùa thắng cuộc đua. Chậm mà chắc sẽ chiến thắng.", emoji: "🏆" },
    ],
  },
  {
    id: 2,
    title: "The Boy Who Cried Wolf",
    title_vi: "Cậu Bé Chăn Cừu",
    thumbnail: "🐑",
    color: "#FFF8E0",
    panels: [
      { en: "A boy watches sheep near a village.", vi: "Một cậu bé trông cừu gần làng.", emoji: "🐑" },
      { en: "He feels bored and wants some excitement.", vi: "Cậu thấy chán và muốn chút náo nhiệt.", emoji: "😐" },
      { en: '"Wolf! Wolf!" he shouts. The villagers run to help.', vi: '"Sói! Sói!" cậu la lên. Dân làng chạy đến.', emoji: "🏃‍♂️" },
      { en: "There is no wolf. The boy laughs at them.", vi: "Không có sói. Cậu bé cười họ.", emoji: "😂" },
      { en: "The next day, he cries wolf again. The villagers come again, angry.", vi: "Hôm sau, cậu lại la sói. Dân làng lại đến, tức giận.", emoji: "😠" },
      { en: "Then a real wolf appears. The boy screams for help.", vi: "Rồi sói thật xuất hiện. Cậu bé la hét cầu cứu.", emoji: "🐺" },
      { en: "No one comes. The wolf eats all the sheep.", vi: "Không ai đến. Sói ăn hết đàn cừu.", emoji: "😭" },
      { en: "Nobody believes a liar, even when they tell the truth.", vi: "Không ai tin kẻ nói dối, dù họ có nói thật.", emoji: "💡" },
    ],
  },
  {
    id: 3,
    title: "The Lion and the Mouse",
    title_vi: "Sư Tử và Chuột Nhắt",
    thumbnail: "🦁",
    color: "#FFF0F0",
    panels: [
      { en: "A lion sleeps under a big tree.", vi: "Sư tử ngủ dưới gốc cây to.", emoji: "🦁" },
      { en: "A little mouse runs across his nose, waking him up.", vi: "Chuột nhắt chạy qua mũi sư tử, đánh thức nó dậy.", emoji: "🐭" },
      { en: '"How dare you!" the lion roars and catches the mouse.', vi: '"Sao dám chứ!" sư tử gầm lên và vồ chuột.', emoji: "😡" },
      { en: '"Please let me go! I might help you one day," the mouse squeaks.', vi: '"Làm ơn thả tôi! Một ngày nào đó tôi có thể giúp ngài," chuột kêu.', emoji: "🥺" },
      { en: '"You? Help me?" laughs the lion, but he lets the mouse go.', vi: '"Cậu? Giúp tôi?" sư tử cười, nhưng thả chuột.', emoji: "😏" },
      { en: "Days later, hunters trap the lion in a net.", vi: "Ít ngày sau, thợ săn bẫy sư tử trong lưới.", emoji: "🕸️" },
      { en: "The mouse hears the lion's roar and chews the net open.", vi: "Chuột nghe tiếng sư tử gầm, liền cắn đứt lưới.", emoji: "🦷" },
      { en: "Even small friends can be great helpers.", vi: "Ngay cả bạn nhỏ cũng có thể giúp ích lớn.", emoji: "🤝" },
    ],
  },
  {
    id: 4,
    title: "The Fox and the Grapes",
    title_vi: "Cáo và Nho",
    thumbnail: "🦊",
    color: "#F5E6FF",
    panels: [
      { en: "A fox walks through a forest on a hot day.", vi: "Cáo đi qua khu rừng trong ngày nóng.", emoji: "🦊" },
      { en: "He sees a bunch of grapes hanging high above.", vi: "Nó thấy chùm nho treo cao trên cao.", emoji: "🍇" },
      { en: '"Those grapes look juicy and sweet!" he thinks.', vi: '"Nho đó trông mọng nước và ngọt quá!" nó nghĩ.', emoji: "🤤" },
      { en: "He jumps and tries to reach the grapes, but they are too high.", vi: "Nó nhảy với tay nho, nhưng cao quá.", emoji: "🦘" },
      { en: "Again and again he jumps, but he cannot get them.", vi: "Hết lần này đến lần khác nó nhảy, nhưng không với tới.", emoji: "😫" },
      { en: "Finally, he gives up and walks away.", vi: "Cuối cùng, nó bỏ cuộc và bỏ đi.", emoji: "😤" },
      { en: '"Those grapes are probably sour anyway," he mutters.', vi: '"Chắc nho đó chua thôi," nó lẩm bẩm.', emoji: "🙄" },
      { en: "It is easy to hate what you cannot have.", vi: "Thật dễ để ghét thứ mình không thể có.", emoji: "💭" },
    ],
  },
  {
    id: 5,
    title: "The Ant and the Grasshopper",
    title_vi: "Kiến và Châu Chấu",
    thumbnail: "🐜",
    color: "#E8F5E9",
    panels: [
      { en: "Summer is warm and the sun shines brightly.", vi: "Mùa hè ấm áp và mặt trời chiếu sáng.", emoji: "☀️" },
      { en: "A grasshopper sings and dances all day long.", vi: "Châu chấu ca hát và nhảy múa suốt ngày.", emoji: "🦗" },
      { en: '"Come work with me before winter comes," says an ant.', vi: '"Đến làm việc với tôi trước khi mùa đông đến," kiến nói.', emoji: "🐜" },
      { en: '"Why work? There is plenty of food today!" laughs the grasshopper.', vi: '"Sao phải làm? Hôm nay còn nhiều thức ăn mà!" châu chấu cười.', emoji: "🎵" },
      { en: "The ant carries grain to her nest every day.", vi: "Kiến mang hạt lúa về tổ mỗi ngày.", emoji: "🏋️" },
      { en: "Winter comes. Snow covers the ground. Food is gone.", vi: "Mùa đông đến, tuyết phủ mặt đất, thức ăn không còn.", emoji: "❄️" },
      { en: "The grasshopper is cold and hungry. He begs the ant for food.", vi: "Châu chấu đói lạnh. Nó xin kiến chút thức ăn.", emoji: "🥶" },
      { en: "Work today so you can rest tomorrow.", vi: "Hãy làm việc hôm nay để ngày mai được nghỉ ngơi.", emoji: "💪" },
    ],
  },
  {
    id: 6,
    title: "The Paper Airplane",
    title_vi: "Chiếc Máy Bay Giấy",
    thumbnail: "✈️",
    color: "#E3F2FD",
    panels: [
      { en: "Mai is a quiet girl who sits by the window in class.", vi: "Mai là một cô gái trầm lặng ngồi cạnh cửa sổ.", emoji: "🌸" },
      { en: "She loves reading books and drawing little flowers in her notebook.", vi: "Cô thích đọc sách và vẽ hoa nhỏ trong vở.", emoji: "📚" },
      { en: "Linh is a boy who never sits still. He runs, he jumps, he laughs loudly.", vi: "Linh là cậu trai không ngồi yên. Cậu chạy, nhảy, cười rất to.", emoji: "🙃" },
      { en: "He sits two rows behind Mai and always watches her from afar.", vi: "Cậu ngồi sau Mai hai hàng và luôn nhìn cô từ xa.", emoji: "👀" },
      { en: 'One afternoon, Linh folds a paper airplane and writes a secret note.', vi: "Một buổi chiều, Linh gấp máy bay giấy và viết một lời nhắn bí mật.", emoji: "✈️" },
      { en: 'The airplane flies across the room and lands softly on Mai\'s desk.', vi: "Chiếc máy bay bay qua lớp và đáp nhẹ xuống bàn Mai.", emoji: "💫" },
      { en: 'Mai unfolds it. Inside it says: "You have a very pretty smile. — L."', vi: 'Mai mở ra. Bên trong ghi: "Bạn có nụ cười rất dễ thương. — L."', emoji: "💌" },
      { en: "Her heart beats fast. She looks back. Linh quickly looks down.", vi: "Tim cô đập nhanh. Cô ngoảnh lại. Linh vội cúi xuống.", emoji: "😳" },
      { en: 'She folds the note carefully and puts it inside her pencil case.', vi: "Cô gấp tờ giấy cẩn thận và cất vào hộp bút.", emoji: "📦" },
      { en: "That night, Mai cannot sleep. She reads the note again and again.", vi: "Đêm đó, Mai không ngủ được. Cô đọc đi đọc lại tờ giấy.", emoji: "🌙" },
      { en: "The next morning, Linh walks to her desk. He looks nervous.", vi: "Sáng hôm sau, Linh bước đến bàn cô. Cậu trông lo lắng.", emoji: "🚶" },
      { en: '"Sorry if I made you uncomfortable," he says, voice shaking.', vi: '"Xin lỗi nếu tớ làm cậu khó xử," cậu nói, giọng run run.', emoji: "🙇" },
      { en: 'Mai looks up and smiles softly. "I liked it," she whispers.', vi: 'Mai ngước lên và mỉm cười nhẹ. "Tớ thích nó," cô thì thầm.', emoji: "😊" },
      { en: "Linh's face turns bright red. He does not know what to say.", vi: "Mặt Linh đỏ bừng. Cậu không biết nói gì.", emoji: "😳" },
      { en: 'Mai takes out a folded paper from her notebook and hands it to him.', vi: "Mai lấy từ vở ra một tờ giấy gấp và đưa cho cậu.", emoji: "🤲" },
      { en: 'He opens it. "The airplane needs a co-pilot. — M."', vi: 'Cậu mở ra. "Máy bay cần một người lái phụ. — M."', emoji: "💕" },
      { en: 'From that day, they sit next to each other. They share lunch.', vi: "Từ ngày đó, họ ngồi cạnh nhau. Họ chia sẻ bữa trưa.", emoji: "🍱" },
      { en: "Mai teaches Linh how to draw flowers. Linh teaches Mai how to whistle.", vi: "Mai dạy Linh vẽ hoa. Linh dạy Mai huýt sáo.", emoji: "🎵" },
      { en: "They walk home together every afternoon under the golden sun.", vi: "Họ cùng đi bộ về nhà mỗi chiều dưới nắng vàng.", emoji: "🌅" },
      { en: "One day, Linh asks, 'Do you think we will always be friends?'", vi: "Một ngày, Linh hỏi: 'Cậu nghĩ chúng ta sẽ mãi là bạn chứ?'", emoji: "🤔" },
      { en: 'Mai thinks for a moment. "I think we will be more," she says quietly.', vi: 'Mai nghĩ một lát. "Tớ nghĩ chúng ta sẽ hơn thế," cô khẽ nói.', emoji: "💗" },
      { en: "Linh takes her hand. It is warm and fits perfectly in his.", vi: "Linh nắm tay cô. Bàn tay cô ấm và vừa vặn trong tay cậu.", emoji: "🤝" },
      { en: "They walk on, not needing words anymore.", vi: "Họ bước tiếp, không cần lời nói nữa.", emoji: "🚶‍♂️" },
      { en: "Weeks pass. Seasons change. Leaves fall and new flowers bloom.", vi: "Tuần trôi qua. Mùa thay đổi. Lá rụng và hoa mới nở.", emoji: "🍂" },
      { en: 'One afternoon, Linh brings Mai a small box wrapped in red paper.', vi: "Một buổi chiều, Linh mang cho Mai một hộp nhỏ gói giấy đỏ.", emoji: "🎁" },
      { en: 'Inside is a bracelet made of blue thread and a tiny paper star.', vi: "Bên trong là vòng tay bằng chỉ xanh và một ngôi sao giấy nhỏ.", emoji: "⭐" },
      { en: '"I made it myself," he says, scratching his head.', vi: '"Tớ tự làm đấy," cậu nói, gãi đầu.', emoji: "😅" },
      { en: "Mai puts it on. She wears it every single day from then on.", vi: "Mai đeo vào. Cô đeo nó mỗi ngày kể từ đó.", emoji: "💙" },
      { en: "Graduation day comes. The whole school gathers in the yard.", vi: "Ngày tốt nghiệp đến. Cả trường tập trung ngoài sân.", emoji: "🎓" },
      { en: "Mai and Linh stand side by side, holding hands.", vi: "Mai và Linh đứng cạnh nhau, nắm tay.", emoji: "👫" },
      { en: 'The principal calls names. Mai\'s name is called first.', vi: "Hiệu trưởng gọi tên. Tên Mai được gọi trước.", emoji: "📢" },
      { en: "She walks up and receives her certificate. Linh claps the loudest.", vi: "Cô bước lên nhận bằng. Linh vỗ tay to nhất.", emoji: "👏" },
      { en: "After the ceremony, they sit under the old banyan tree.", vi: "Sau buổi lễ, họ ngồi dưới gốc cây đa già.", emoji: "🌳" },
      { en: '"What happens now?" Linh asks, looking at the clouds.', vi: '"Giờ thì sao?" Linh hỏi, nhìn lên mây.', emoji: "☁️" },
      { en: '"We grow up. We study. We find our way," Mai replies.', vi: '"Chúng ta lớn lên, học hành, tìm đường đi," Mai đáp.', emoji: "💭" },
      { en: '"But I want you in my way," Linh says without looking at her.', vi: '"Nhưng tớ muốn cậu trong con đường của tớ," Linh nói không nhìn cô.', emoji: "🥹" },
      { en: "Mai leans her head on his shoulder. The wind blows softly.", vi: "Mai tựa đầu vào vai cậu. Gió thổi nhẹ.", emoji: "🍃" },
      { en: '"Then stay," she says. And that is all he needs to hear.', vi: '"Vậy ở lại đi," cô nói. Và đó là tất cả cậu cần nghe.', emoji: "🤗" },
      { en: "Years later, Mai becomes a teacher at the same school.", vi: "Nhiều năm sau, Mai trở thành giáo viên ở chính ngôi trường ấy.", emoji: "👩‍🏫" },
      { en: "Linh opens a small bookstore near the school gate.", vi: "Linh mở một hiệu sách nhỏ gần cổng trường.", emoji: "📖" },
      { en: "Every morning, Mai stops by for a cup of tea and a kiss.", vi: "Mỗi sáng, Mai ghé qua uống trà và hôn nhẹ.", emoji: "☕" },
      { en: "Children run past the shop, laughing and shouting.", vi: "Trẻ con chạy qua hiệu sách, cười đùa.", emoji: "🏃‍♀️" },
      { en: "Sometimes Linh folds paper airplanes for them.", vi: "Thỉnh thoảng Linh gấp máy bay giấy cho chúng.", emoji: "✈️" },
      { en: "And every single plane carries a quiet wish: love lasts.", vi: "Và mỗi chiếc máy bay mang một điều ước thầm: tình yêu bền lâu.", emoji: "💫" },
      { en: "Love does not always begin with fireworks or grand words.", vi: "Tình yêu không phải luôn bắt đầu bằng pháo hoa hay lời hoa mỹ.", emoji: "💕" },
      { en: "Sometimes it begins with a paper airplane, a folded note, and a brave heart.", vi: "Đôi khi chỉ cần một máy bay giấy, một mảnh giấy gấp, và một trái tim dũng cảm.", emoji: "🕊️" },
      { en: "And that is enough to write a story that lasts a lifetime.", vi: "Và thế là đủ để viết nên câu chuyện kéo dài cả đời.", emoji: "📜" },
    ],
  },
  {
    id: 7,
    title: "The Wind and the Sun",
    title_vi: "Gió và Mặt Trời",
    thumbnail: "🌬️",
    color: "#FFF3E0",
    panels: [
      { en: "The Wind and the Sun argue about who is stronger.", vi: "Gió và Mặt Trời cãi nhau xem ai mạnh hơn.", emoji: "🌬️" },
      { en: "They see a traveler walking down the road with a warm coat.", vi: "Họ thấy một người đi đường đang mặc áo khoác ấm.", emoji: "🧥" },
      { en: "\"I can make him take off his coat!\" says the Wind.", vi: "\"Tôi có thể làm anh ấy cởi áo!\" Gió nói.", emoji: "💪" },
      { en: "The Wind blows hard and cold, but the traveler holds his coat tighter.", vi: "Gió thổi mạnh và lạnh, nhưng người đi đường giữ áo chặt hơn.", emoji: "🌪️" },
      { en: "The Sun smiles warmly and shines bright gentle rays.", vi: "Mặt Trời mỉm cười ấm áp và chiếu những tia sáng dịu dàng.", emoji: "☀️" },
      { en: "The traveler feels warm, smiles, and takes off his coat.", vi: "Người đi đường cảm thấy ấm, mỉm cười và cởi áo khoác.", emoji: "😊" },
      { en: "The Sun wins. Kindness and warmth are stronger than force.", vi: "Mặt Trời thắng. Sự dịu dàng và ấm áp mạnh hơn vũ lực.", emoji: "🏆" },
      { en: "Gentleness can achieve what force cannot.", vi: "Dịu dàng có thể đạt được điều mà vũ lực không thể.", emoji: "💡" },
    ],
  },
  {
    id: 8,
    title: "The Crow and the Pitcher",
    title_vi: "Quạ và Bình Nước",
    thumbnail: "🐦‍⬛",
    color: "#ECEFF1",
    panels: [
      { en: "A thirsty crow searches everywhere for water on a hot day.", vi: "Một con quạ khát nước tìm kiếm khắp nơi trong ngày nóng.", emoji: "🐦‍⬛" },
      { en: "It finds a pitcher with a little water at the bottom.", vi: "Nó tìm thấy một cái bình có chút nước ở đáy.", emoji: "🏺" },
      { en: "The crow tries to drink, but its beak cannot reach the water.", vi: "Quạ cố uống nhưng mỏ không với tới nước.", emoji: "😫" },
      { en: "The crow thinks hard. It looks around for something to help.", vi: "Quạ suy nghĩ. Nó nhìn quanh tìm thứ gì đó giúp ích.", emoji: "🤔" },
      { en: "It sees small pebbles on the ground and has an idea.", vi: "Nó thấy những viên sỏi nhỏ trên mặt đất và nảy ra ý tưởng.", emoji: "🪨" },
      { en: "One by one, the crow drops pebbles into the pitcher.", vi: "Từng viên một, quạ thả sỏi vào bình nước.", emoji: "👄" },
      { en: "The water level rises slowly with each pebble!", vi: "Mực nước dâng lên từ từ theo từng viên sỏi!", emoji: "📈" },
      { en: "At last, the water reaches the top, and the crow drinks happily.", vi: "Cuối cùng, nước lên tới miệng bình, và quạ uống thỏa thích.", emoji: "💧" },
      { en: "Where there is a will, there is a way. Think and solve!", vi: "Có chí thì nên. Hãy suy nghĩ và giải quyết!", emoji: "💡" },
    ],
  },
  {
    id: 9,
    title: "The Oak and the Reed",
    title_vi: "Cây Sồi và Cây Lau",
    thumbnail: "🌳",
    color: "#E8F5E9",
    panels: [
      { en: "A tall, proud oak tree stands by the riverbank.", vi: "Một cây sồi cao lớn, kiêu hãnh đứng bên bờ sông.", emoji: "🌳" },
      { en: "Next to it, a thin reed bends gently in the breeze.", vi: "Bên cạnh nó, một cây lau mảnh khảnh uốn mình trong gió.", emoji: "🌾" },
      { en: "\"You are so weak! Even the wind moves you,\" laughs the oak.", vi: "\"Cậu yếu ớt quá! Gió nhẹ cũng lay động,\" sồi cười.", emoji: "😏" },
      { en: "\"Better to bend than to break,\" whispers the reed.", vi: "\"Thà uốn cong còn hơn gãy,\" lau thì thầm.", emoji: "😌" },
      { en: "One night, a terrible storm comes with powerful winds.", vi: "Một đêm, cơn bão khủng khiếp đến với những cơn gió mạnh.", emoji: "🌪️" },
      { en: "The oak stands tall and fights the wind with all its might.", vi: "Sồi đứng thẳng và chống chọi với gió bằng tất cả sức mạnh.", emoji: "💪" },
      { en: "The reed bends low, letting the wind pass over it.", vi: "Lau cúi thấp, để gió lướt qua.", emoji: "🌾" },
      { en: "\"CRACK!\" The oak cannot bend, and it snaps in half.", vi: "\"RẮC!\" Sồi không thể uốn cong, và nó gãy làm đôi.", emoji: "💔" },
      { en: "The reed stands up again, safe and unharmed.", vi: "Lau đứng dậy, an toàn và không hề hấn gì.", emoji: "🌾" },
      { en: "It is better to be flexible than to be stubborn.", vi: "Dẻo dai tốt hơn cứng nhắc.", emoji: "💡" },
    ],
  },
  {
    id: 10,
    title: "The Dog and His Reflection",
    title_vi: "Con Chó và Cái Bóng",
    thumbnail: "🐕",
    color: "#FFF8E1",
    panels: [
      { en: "A dog carries a juicy bone in his mouth across a bridge.", vi: "Một con chó ngậm một khúc xương ngon lành đi qua cầu.", emoji: "🐕" },
      { en: "He looks down at the water and sees another dog.", vi: "Nó nhìn xuống nước và thấy một con chó khác.", emoji: "🌉" },
      { en: "That dog has a bone too — it looks bigger and better!", vi: "Con chó đó cũng có xương — trông to hơn và ngon hơn!", emoji: "🦴" },
      { en: "\"I want that bone!\" the greedy dog thinks angrily.", vi: "\"Ta muốn khúc xương đó!\" con chó tham lam nghĩ.", emoji: "😈" },
      { en: "He opens his mouth to bark at the other dog.", vi: "Nó há mồm định sủa con chó kia.", emoji: "🐕" },
      { en: "SPLASH! His own bone falls into the water and is gone.", vi: "ÒM! Khúc xương của nó rơi xuống nước và biến mất.", emoji: "💧" },
      { en: "The other dog was only his own reflection.", vi: "Con chó kia chỉ là cái bóng của chính nó.", emoji: "😭" },
      { en: "Greed loses what you already have. Be grateful!", vi: "Tham lam làm mất những gì bạn đã có. Hãy biết đủ!", emoji: "💡" },
    ],
  },
  {
    id: 11,
    title: "The Frogs Who Desired a King",
    title_vi: "Những Chú Ếch Muốn Có Vua",
    thumbnail: "🐸",
    color: "#E0F2F1",
    panels: [
      { en: "A group of frogs live happily in a pond with no leader.", vi: "Một đàn ếch sống vui vẻ trong ao không có thủ lĩnh.", emoji: "🐸" },
      { en: "\"We need a king to rule us!\" they complain to Jupiter.", vi: "\"Chúng tôi cần một vị vua!\" chúng kêu ca với thần Jupiter.", emoji: "😤" },
      { en: "Jupiter throws a big log into the pond. SPLASH!", vi: "Jupiter ném một khúc gỗ lớn xuống ao. ÒM!", emoji: "🪵" },
      { en: "The frogs hide in fear. The log does not move.", vi: "Ếch sợ hãi trốn đi. Khúc gỗ không động đậy.", emoji: "😱" },
      { en: "\"This king is too quiet!\" The frogs climb on the log and jump around.", vi: "\"Vua này im lặng quá!\" Ếch trèo lên gỗ và nhảy nhót.", emoji: "🐸" },
      { en: "\"Send us a real king!\" they beg again.", vi: "\"Gửi cho chúng tôi một vị vua thực sự!\" chúng lại cầu xin.", emoji: "🙏" },
      { en: "Jupiter sends a stork. The stork eats the frogs one by one.", vi: "Jupiter gửi một con cò. Cò ăn thịt ếch từng con một.", emoji: "🐍" },
      { en: "\"We should have been happy with the log king!\" they cry.", vi: "\"Đáng lẽ chúng tôi nên hài lòng với vua gỗ!\" chúng khóc.", emoji: "😭" },
      { en: "Be careful what you wish for. Sometimes no ruler is best.", vi: "Cẩn thận với điều bạn ước. Đôi khi không có người cai trị là tốt nhất.", emoji: "💡" },
    ],
  },
];
